### ISSUE TITLE
1.2.19 : SObject row was retrieved via SOQL without querying the requested field

### ISSUE THREAD

**Issue by mickster04** [jamessimone/apex-rollup#102]
Sorry to effectively re-open this one:

Calc Item					Installment
Rollup Operation			FIRST
Calc Item Where Clause		Cancelled__c = false AND Amount_Outstanding__c > 0
Order By (First/Last)		Due_Date__c

10:45.0 (415860128)|FATAL_ERROR|System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: Installment__c.Cancelled__c

Class.RollupEvaluator.WhereFieldCondition.getFieldValue: line 547, column 1
Class.RollupEvaluator.WhereFieldCondition.equals: line 472, column 1
Class.RollupEvaluator.AndConditionalGrouping.conditionallyEquals: line 424, column 1
Class.RollupEvaluator.ConditionalGrouping.equals: line 386, column 1
Class.RollupEvaluator.WhereFieldEvaluator.innerMatches: line 176, column 1
Class.RollupEvaluator.WhereFieldEvaluator.matches: line 166, column 1
Class.RollupEvaluator.CombinedEvaluator.matches: line 90, column 1
Class.RollupCalculator.winnowItems: line 239, column 1
Class.RollupCalculator.FirstLastRollupCalculator.performRollup: line 995, column 1
Class.Rollup.getRollupVal: line 2827, column 1
Class.Rollup.getUpdatedLookupItemsByRollup: line 2773, column 1
Class.Rollup.process: line 2492, column 1
Class.Rollup.runCalc: line 318, column 1
Class.Rollup.processDelegatedFullRecalcRollup: line 2444, column 1
Class.RollupFullBatchRecalculator.execute: line 35, column 1
15:10:45.0 (440016414)|CODE_UNIT_FINISHED|RollupFullBatchRecalculator
15:10:45.0 (440037191)|EXECUTION_FINISHED

**Comment by jamessimone** [comment]
@mickster04 never mind - I see where the problem is. This is an issue only for first/last/average operations, but I apologize for the oversight. I’ll push out the updated version fixing this (for good) tomorrow morning

**Comment by mickster04** [comment]
Yup from the app using the mdt records

**Comment by jamessimone** [comment]
@mickster04 you should be all set on this one with the latest package version!
