### ISSUE TITLE
Error Installing into Sandbox: RollupCalculatorTests: Variable does not exist: QuickText

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#118]
I'm trying to install into my sandbox and I'm getting the following error. Any recommendations?

```
Variable does not exist: QuickText | RollupCalculatorTests: Variable does not exist: QuickText
-- | --
Variable does not exist: QuickText.Channel | RollupCalculatorTests: Variable does not exist: QuickText.Channel
Invalid type: QuickText | RollupCalculatorTests: Invalid type: QuickText
Invalid type: QuickText | RollupEvaluatorTests: Invalid type: QuickText
Variable does not exist: QuickText | RollupEvaluatorTests: Variable does not exist: QuickText
Method does not exist or incorrect signature: void matches(QuickText) from the type Rollup.Evaluator | RollupEvaluatorTests: Method does not exist or incorrect signature: void matches(QuickText) from the type Rollup.Evaluator

```
![image](https://user-images.githubusercontent.com/643517/121973250-b1805000-cd31-11eb-8242-c405b0e8b4fd.png)

**Comment by jamessimone** [comment]
@jkenzer what kind of sandbox are you installing this into? `QuickText` has been available since API version 44 - it should definitely be there!

**Comment by jkenzer** [comment]
It's a full copy sandbox of my production instance. After reading your reply, I checked and noticed I don't have it enabled. Is that a requirement?

**Comment by jkenzer** [comment]
That did. I enabled QuickText and the install succeeded.

**Comment by jamessimone** [comment]
Great to hear! Let me know if you have any other issues!
