### ISSUE TITLE
Error running Recalcuate Rollup from Parent

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#125]
@jamessimone It looks like the Recalculate Rollup is working as expected now. It only generated 1 batch. However, I think as a side effect to the DateTime comparison changes, it's erroring out:

![image](https://user-images.githubusercontent.com/643517/122783990-e9722080-d266-11eb-8c4d-fe8444ade84a.png)

The field Grant_Date_From_Grant__c is a Date formula field (not a DateTime). I'm not sure if I have the clause formatted incorrectly (no quotes, yyyy-mm-dd) or if it's reading the field type incorrectly:

![image](https://user-images.githubusercontent.com/643517/122784305-3655f700-d267-11eb-8224-fbeb731b8e93.png)

**Comment by jamessimone** [comment]
@jkenzer it shouldn't matter if it's a formula field; I will fix this issue, but for now you should be good to go by changing the date to this `2021-04-01 00:00:00`

**Comment by jkenzer** [comment]
Updating it to 2021-04-01 00:00:00 fixed the issue. Do you want me to leave this open to allow for a date without the time designation?

**Comment by jamessimone** [comment]
@jkenzer yes please! I have just fixed the underlying issue and will look to get this updated version out in the next day or so.
