### ISSUE TITLE
Error running Recalculate Rollup from Rollup App

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#126]
@jamessimone Another new issue, but might be related to Issue #125. When I attempt to run the rollup from the app, I get a governor limit error.

![image](https://user-images.githubusercontent.com/643517/122784835-a9f80400-d267-11eb-99a3-84b259bc9740.png)

![image](https://user-images.githubusercontent.com/643517/122784864-b2503f00-d267-11eb-9c3d-fe7a7433cf51.png)

**Comment by jamessimone** [comment]
@jkenzer That's quite interesting. Can you try tweaking the `BatchChunkSize__c` in your `Org_Default` Rollup Control CMDT to something more manageable like 100? Rollup batches based on the number of parent records, but presumably some of your parent records have quite a bit in the way of children records; I will have to figure out something for the base recalculation route to more gracefully handle this, but in the meantime I think lowering the Batch Chunk Size field will help to address this.

**Comment by jkenzer** [comment]
@jamessimone After adding the time suffix as per #125, this issue resolved itself. I tried it once with just Grants YTD and again with all three checked, and they both batched into 69 batches and ran fine.

**Comment by jamessimone** [comment]
@jkenzer Let's keep this issue open for now - I'd like to at least tweak the error message being returned, in that case. Thanks for updating me!

**Comment by jamessimone** [comment]
After some thought, decided to close this one as the fix will be in #125, and the error message returned here was technically correct.
