### ISSUE TITLE
Investigate discrepancies with recalculate CMDT route from button/app

### ISSUE THREAD

**Issue by jamessimone** [jamessimone/apex-rollup#127]
Reported by @solo-1234:

* I am rolling up to a custom object
* Junction records connect the record to a contact
* Rollup 1 filters on a child field and a contact field
* Rollup 2 only filters on a child field

Result - updating junction object to no longer meet criteria for Rollup 1 & 2 _only_ correctly clears out the field on Rollup 2

**Comment by solo-1234** [comment]
Seems like this only happens when the rollup field should be switching from 1 to 0. 

So if I have 2 junction records that meet criteria, the rollup fields both say 2. If I change one junction record so that it doesn't meet criteria for either rollup, they both change to 1. And if I do the same with the other junction record, Rollup 1 stays the same but Rollup 2 changes to 0 (as it should).

**Comment by jkenzer** [comment]
@jamessimone I'm noticing a discrepancy too. I have three separate roll-ups on my junction object. One that does the total amount for the current year, one that does the total amount for the previous year, and one that does a count of the previous year. When I used the button on the parent, all three calculate correctly.

If I use the Rollup App (as in the screenshot), I get totally different numbers. The Rollup app undercounts, similar to how the button did before you fixed the last issue I reported.

![image](https://user-images.githubusercontent.com/643517/123491993-07c07f00-d5cd-11eb-827d-0fc81dd24959.png)

I've tried both methods with clearing out the fields or leaving them populated from the previous run. Having the fields populated with values before running appears to have no difference than if they are empty.

**Comment by jamessimone** [comment]
It makes sense that there’s no difference if there are values or not, as both do full recalculation. Any where clause on those Rollup__mdt records I should be aware of?

**Comment by solo-1234** [comment]
The interesting thing is that with my bug that prompted this issue, when I manually clear the rollup field or set it to zero (when it's showing 1 but should be zero), the recalc button keeps it at blank/zero.

**Comment by jkenzer** [comment]
> Any where clause on those Rollup__mdt records I should be aware of?

Two are:
`Grant_Date_From_Grant__c >= 2020-04-01 00:00:00 AND Grant_Date_From_Grant__c < 2021-04-01 00:00:00`

and the other is:
`Grant_Date_From_Grant__c >= 2021-04-01 00:00:00`

**Comment by jamessimone** [comment]
@jkenzer for the parent record(s) you are updating, how many children records can there be? The button and the app use the exact same code path — except for one thing:

- the value defined on your Rollup Control CMDT for this rollup (the org default if you don’t have any custom ones) for Batch Chunk Size. It defaults to 2000, but you might have modified it.

If you are dealing with large numbers of children records, I’m realizing it could be possible at present for children to be in multiple batches with the same parent, and perhaps the updates are stepping on one another. I can partially address this in the upcoming release by adding in an ORDER BY clause so that the calc items are fetched by parent in the full recalculation instances. This could still potentially have issues if the number of records on a single parent exceeded the Batch Chunk Size, but there are potential workarounds to that as well.

**Comment by jkenzer** [comment]
@jamessimone This makes perfect sense. While testing using the button, the max number of child records has been well under 100. However, when I'm running from the App, there are over 18,000 child records spread over 1,137 parent records.

I have my settings as the defaults:

- Max Lookup Rows Before Batching: 3000
- Batch Chunk Size: 2000

I do have one parent record that has over 3,376 children. When I ran that with the button, it split into 2 batches and the final output of the rollup that does just a count was 1,376.

Because of the volume to run it across all parent records, I'm concerned that even if I increased the chunk size, there could be parent records that are split across chunks. Thoughts?

**Comment by jamessimone** [comment]
@jkenzer I have a solution for this that will look at the number of children records per parent; at the expense of an extra query, if the number of children records exceeds the max batch chunk size, I’ll break that particular parent out into a separate batch job that only calculates for that parent. It’s possible that I can do this without the separate batch job, too; I may try that and then break it out if necessary (where “necessary” means “if the heap size limits get exceeded by keeping track of all the parents between batches”). Thanks for the feedback on this one, I feel we were quickly able to diagnose the issue and I’ll be able to include this in the next release!

**Comment by jamessimone** [comment]
@jkenzer those updates have been released in the latest version - I don't think that I have (as of yet) tackled the original issue reported by @solo-1234, but I am hoping the changes just pushed will address the issue we were discussing.

**Comment by solo-1234** [comment]
Thanks for working on this! I just installed the latest version but it doesn't seem to have helped my issue.

**Comment by jamessimone** [comment]
@solo-1234 sorry to hear that, but not exactly surprised. I am hopeful to make more progress on your specific issue once I've wrapped up the scalability issues @jkenzer has brought up here and in #132. I will get to this!

**Comment by solo-1234** [comment]
Thanks for the update!

**Comment by jamessimone** [comment]
@solo-1234 are these COUNT or COUNT_DISTINCT rollups? I may have some other clarifying questions for you, but starting to unravel this issue. Thank you!

**Comment by solo-1234** [comment]
They are COUNT. Thanks!

**Comment by jamessimone** [comment]
@solo-1234 I've tweaked a few behaviors surrounding both full recalcs and the situation where an item's old version matches and the updated version does not; I can't say for certain whether or not anything I did directly helped your situation, but I would be curious to know!

**Comment by solo-1234** [comment]
Thanks for working on this! Seems like the issue is not resolved yet though...

**Comment by jamessimone** [comment]
Ugh. I might have to request some logs from you with the Is Rollup Logging flag enabled, if you’re game. I’m sorry I haven’t been able to figure it out without those 😭

**Comment by jkenzer** [comment]
@jamessimone All is now good on my side. Both the button and the CMDT work without issues and produce the correct values!!! Many thanks.

**Comment by jamessimone** [comment]
@jkenzer glad to hear it!

**Comment by jamessimone** [comment]
@solo-1234 I know we were chatting about a few different things regarding this on Friday, but I wanted to see if you had been able to reproduce the issue you were experiencing in your scratch org?

**Comment by solo-1234** [comment]
Thanks for following up! I was not able to replicate it in my scratch org, and am now trying to get a consistent replication in my org so I can compare the two. It's possible that last week's update may have changed things (and I wonder if my testing last week was on a cached version of the app since I'm not seeing the same behavior now). Will keep you posted!

**Comment by solo-1234** [comment]
Seems like this issue has been resolved! I will keep an eye out but as of now am unable to replicate it in my org.

Thanks for your help!

**Comment by solo-1234** [comment]
Would the recommended way to recalc the lookups when a field is changed on Contact be a contact after-save flow that fetches the child junction records and passes them to the CMDT apex action? I am going to give that a spin.

**Comment by jamessimone** [comment]
@solo-1234 That's one way to do it, yes. Alternatively if `Contact` is the parent, you can use the `Is Rollup Started From Parent` flag and pass the contact record itself.

**Comment by solo-1234** [comment]
Thanks! What context would I provide? Should it be UPDATE? I don't have access to prior records (for the children, since they weren't actually edited), can I just leave that out?

**Comment by solo-1234** [comment]
It won't let me leave out the prior records so I passed the same collection of children to both vars, but it doesn't seem like the rollup ran (it still shows the old # until I click the Recalc button).

I tried with INSERT context and got the same results.

**Comment by jamessimone** [comment]
@solo-1234 wait really? You should definitely be able to omit the prior records ... the context should be INSERT, most likely, based on your use-case - what other variables in the flow do you have filled out?

**Comment by solo-1234** [comment]
When I ran it as UPDATE without prior it threw an error
`Error element Run_Rollups (FlowActionCall). An Apex error occurred: System.IllegalArgumentException: Prior records to rollup collection required for rollup context: UPDATE`

I was running in as UPDATE and as INSERT with passing in both collections and both did not do anything.

I just tried now running it as INSERT without the prior collection, and it's not updating the rollup that it should update, but it's incrementing another rollup which it shouldn't (acting as if there is a new junction record when there isn't).

The only vars I am passing in are context, defer processing (false), and records to rollup.

Thanks for your help!

**Comment by solo-1234** [comment]
I wonder if the issue with running in UPDATE context is that the two record collections don't show any differences so it thinks it doesn't need to recalculate

**Comment by jamessimone** [comment]
@solo-1234 yes, that's for sure the issue with the UPDATE approach. Are you getting all records associated with the parent in question? I am wondering if you don't also need to set the Is Full Record Set variable, in that case (for INSERT)

**Comment by solo-1234** [comment]
I am getting all the child (junction) records associated with the contact that was edited, but am rolling up to a custom object and am not getting all the records associated with that record. Do you think I need to?

I'll try the Is Full Record Set flag.

**Comment by solo-1234** [comment]
Can I set the Is Full Record Set via the cmdt rollup action? I don't see an option for that.

**Comment by jamessimone** [comment]
@solo-1234 it's a flag on the CMDT record - so yes, you can!

**Comment by solo-1234** [comment]
Hmm... will that affect all times this rollup runs? Most of the time it'll be running triggered from the child object and I don't want to mess that up.

**Comment by jamessimone** [comment]
Ah. Hmm. It seems we're at an impasse. I thought you might say that. What
else can I do to help?

**Comment by solo-1234** [comment]
I'm trying to think of how I could get around this. Is there any way to run rollups in update context without prior records?

Does Rollup.RunFromApex with update context use prior records? If not, I'll try that.

Thanks for all your help with this!

**Comment by solo-1234** [comment]
I'm trying the new version and running the rollups from the parent, but it seems that I can't use Is Full Record Set because I'm not passing in all the children for the parent I'm rolling up to (I only have all the children for the parent that was edited). So I switched that to false and changed the context to UPDATE but now it's throwing an error since it doesn't have the var for prior records.

Sounds like we might need a new context for rolling up from parent, which is neither INSERT nor UPDATE. Maybe something called REFRESH? 

Is this what the Recalc Rollups flexipage button does? Could we possibly hook into that via a flow action?

Should I start a new issue for this question?

**Comment by jamessimone** [comment]
@solo-1234 yes let’s make a new issue for this - I like the REFRESH context idea. How many parent records will we be talking here? It’s likely I’ll be able to make this flow through the same way as the recalc button, but good to get an idea for the numbers still

**Comment by solo-1234** [comment]
I'll do that- thanks!

For this particular use case, if I could run it from the children (junction records in this situation), it would usually be rolling up 1-2 children, but occasionally as many as 5-10. If I would be rolling it up from the parent, it would be the parents of all those children, and each parent would have probably 50 children on average.

Note also in this situation I currently have 4 rollups from this child to this parent, but only 2 of them would need to be recalculated when contacts are edited.

**Comment by solo-1234** [comment]
See #141
