### ISSUE TITLE
Javascript Error on Recalculate Rollup CMDT (1.2.31)

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#130]
When running from the Rollup App, I'm getting a toast message "Bind must be called on a function"

![image](https://user-images.githubusercontent.com/643517/123828830-be1ab180-d8b6-11eb-823c-4d8d6b0604ae.png)

This does not stop the RollupFullBatchRecalculator from running. Looks to just be a UI error.

**Comment by jamessimone** [comment]
I believe this is a caching issue - I had that message occur one time when
I *first* deployed the new version of the LWC, but it never showed up again
after that.

**Comment by jkenzer** [comment]
I tried clearing my cache as well as I have my browser dev tools set to Disable cache when open, and I'm still getting the error. Any other suggestions?

Here's from the console:

![image](https://user-images.githubusercontent.com/643517/123833677-73e7ff00-d8bb-11eb-83c3-f553f0e0ae81.png)

The error keeps generating as the page is running:

![image](https://user-images.githubusercontent.com/643517/123833742-84987500-d8bb-11eb-881d-38671d26e1be.png)

**Comment by jamessimone** [comment]
Interesting. I found the issue. I will push out a fix for this later today
after reviewing your other feedback!

**Comment by jamessimone** [comment]
Hmm. In looking at my change ... it's not actually changing anything. Which is to say that I got that message once or twice more after receiving this issue, and then it went away on its own. Are you still experiencing the issue?

**Comment by jkenzer** [comment]
Yeah, I'm still getting it. I tried in Firefox and the error is slightly different:

![image](https://user-images.githubusercontent.com/643517/123877758-ad882c80-d8f2-11eb-9828-a6d5a9b8e891.png)

And in Safari, which I have never used in the sandbox I'm testing in so it couldn't be cached:

![image](https://user-images.githubusercontent.com/643517/123877796-bc6edf00-d8f2-11eb-82bd-d8fd5de74343.png)
