### ISSUE TITLE
Too Many SOQL Queries

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#132]
While running a full recalc from the App, I've gotten this two out of the three times. I am making sure that all batches are complete before testing again:

![image](https://user-images.githubusercontent.com/643517/123833263-076d0000-d8bb-11eb-8164-2be8f1109cd1.png)

Is there something more I can provide here to get debug?

**Comment by jamessimone** [comment]
If you're comfortable enabling `Is Rollup Logging Enabled` on the Org_Default Rollup Control record and sending along one of the Batch debug logs generated by you doing this, that would help a lot. I'm really surprised to see this message here - to me it would seem to indicate that you have 200+ parent records with more than 2000 child records each that are being recalculated. I'll be able to pinpoint the exact nature of the issue with a log, or with a stacktrace even about where that error is originating from, as well as some ballpark figures about how many parent/child records _should_ be getting included!

**Comment by jkenzer** [comment]
I've noticed a different behavior while running. If I only select one of the three rollups, I get "Too many query rows: 50001".

![image](https://user-images.githubusercontent.com/643517/123883509-01e4d980-d8fe-11eb-82e5-3a3555fce435.png)

If I select all three, it runs but generates the Too Many SOQL Queries error. I'll send these logs via email too.

**Comment by jamessimone** [comment]
OK, I've fixed the "Too many query rows" issue locally, and I now know how the "Too many SOQL queries" error is being generated. Working on the fix for that now.

**Comment by jamessimone** [comment]
@jkenzer while I work on the fix for this, I think you can get the full recalculation working by lowering the Batch Chunk Size variable down to something like 190 on the Org Default Rollup Control. Obviously that’s a lot more batches to work through, overall, but I’d be curious to hear if you ran into issues with that approach.

**Comment by jamessimone** [comment]
@jkenzer I've released some changes that will hopefully help with both of the errors that you were getting here. If you get the chance to update, please let me know. I will probably be a bit slower in responding to things this holiday weekend, but I am committed to getting this working for you and I hope you'll bear with me.

**Comment by jkenzer** [comment]
@jamessimone Totally understand about the holiday and I appreciate the continued work.

Bad news: I ran the new release on my fresh sandbox from the app, and got the same Too many query rows error. Log is coming via email.

**Comment by jamessimone** [comment]
Thanks for sending along the log! I will keep you updated as to my progress on this; with luck we will get this fixed up early next week.

**Comment by jamessimone** [comment]
@jkenzer hoping to have finally quashed this one with the latest release. Please let me know! I am once more going to have limited availability through the rest of this week, but I will keep you up to date here in the event of further issues.
