### ISSUE TITLE
new context for flow based rollups - REFRESH

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#141]
Sometimes it would be useful to run CMDT based rollups without specifying INSERT (which will consider the children new records and add to the tally) or UPDATE (which requires a records prior collection and will compare the two to see which rollups to recalculate).

I would call this context REFRESH (or something to that effect) since it doesn't presume to know what needs to be changed, and instead runs a fresh calculation.

Two use cases I can see for this are:

1. When rolling up junction records to parentA where the rollups are filtered on fields from parentB - ideally I'd run this from the children (the junction records). For example, if a specific parentB field is edited, I'd Get Records to fetch the children and pass them in to be re-calculated, to update the rollups on parentA.
2. When rolling up records on a schedule, neither INSERT nor UPDATE context makes sense since we don't know if there were any changes since the last calculation. These rollup calculations should be done fresh. This could be done either from the children or from the parent, I'm not sure if there's one I'd prefer or if it would depend on the use case, or if only one way was possible I'd use that one :). This would be very similar (I think) to the Recalculate Rollups flexipage button.

Let me know if any further clarification would be helpful. Thanks for all your efforts so far on this!

**Comment by jamessimone** [comment]
@solo-1234 this is super helpful. I think both starting from the parent and child make sense. Under the hood, I’ll probably use REFRESH in conjunction with `Is Full Record Set`, in the sense that refresh will both:

- query for the additional children records for applicable parents
- reset the parent rollup field since all children are present

thanks for submitting this and I will include this functionality in the next release, `v1.2.35` — @jongpie and I are also working on #68 to include in that release, but I’m feeling good about finishing that up tomorrow or Wednesday latest, so I’m hopeful to release by Friday again for the whole thing.

**Comment by solo-1234** [comment]
Sounds like that will be exactly what's needed here! And linking with nebula logger sounds really neat too...
Thanks!

**Comment by solo-1234** [comment]
Nice! Will it work both when rolling up from child and from parent?

**Comment by jamessimone** [comment]
@solo-1234 yes it will. I do have to put out a small bug fix for this, the Calc Item Where Clause (if you’re using one) doesn’t carry through properly. I’ll either be releasing that tonight or tomorrow morning to patch that. It’s why I didn’t ping you here!

**Comment by solo-1234** [comment]
Ah, nice!

**Comment by jamessimone** [comment]
@solo-1234 OK, with `v1.2.36` which has just been released, everything should be good to go

**Comment by solo-1234** [comment]
Thanks for the rollup update!

I am now seeing inconsistent results with the recalc rollup buttons. On the previous version, if I changed a field on the junction object so that that record no longer met rollup criteria, and clicked refresh, the rollup that just filters on that field AND the rollup that filters on that field plus a parent field would be reduced by one. In my sandbox with the new version, only the rollup that only filters on the junction record field changes.

Seems that my flow which runs the rollups from the parent is acting the same way. Any ideas?

**Comment by solo-1234** [comment]
Actually, it looks like sometimes it is updating properly and sometimes it's not. I will do more investigating and see if I can pin down what's going on.

Thanks!

**Comment by jamessimone** [comment]
Hmm. Interesting. Keep me updated! I will go back through and try to see why that would be happening ...

**Comment by solo-1234** [comment]
It's really making my head spin! Now it seems like the recalc button is working properly, but rolling up from parent with REFRESH is only raising rollup counts, but not lowering (when the parent record was edited to stop meeting criteria).

Could that make sense?

**Comment by solo-1234** [comment]
And when that happens, sometimes pressing recalc fixes the counts and sometimes it doesn't :(

**Comment by solo-1234** [comment]
Okay so I did a whole bunch of testing. It seems that some of the issues I was seeing were due to me reloading the page too quickly, before the rollups finished running.

Aside from that, I am seeing some issues when editing child records so they no longer meet criteria. The rollup which just looks at the child record for criteria recalculates, but the rollup which has the additional criteria on Contact does not recalculate down. Clicking the button to manually recalculate doesn't help but if I manually adjust the field to the proper number, and then click recalc, it stays at the correct number.

 Another issue I saw is with 2 records where the contact matches the criteria, but the child does not. When I edit both children at once to meet the criteria, both rollups should say 2, but the one that filters on the contact field only says 1. Clicking the recalc button fixed that.

There may be other scenarios where things don't recalc as they should - I'd have to do some more testing - but these are two of them.

Hope you can help figure this out - thanks!

**Comment by jamessimone** [comment]
@solo-1234 sorry for the slow response on this - crazy day. I am going to be adding in some additional logging in the next version under the FINE logging level to add greater clarity surrounding filtering issues caused by the Calc Item Where Clause.

I also haven’t thoroughly tested with filtering on parent fields from Flow, in general; that could certainly be the issue that you’re describing. I’ll have to get some concrete tests stood up to clarify where things are going wrong here. Thank you for your patience! Hopefully I can get these issues addressed in the next version.

**Comment by solo-1234** [comment]
No worries! The extra logging sounds like it'll be helpful. Meanwhile I will see if I can replicate this in a scratch org if I get a chance.

Thanks for your help!
