### ISSUE TITLE
Problems with Flow and Calc Item Where Clause filtering

### ISSUE THREAD

**Issue by jamessimone** [jamessimone/apex-rollup#149]
* ~~Parent field filtering on updates may be broken (parent filtering on inserts is confirmed working)~~
* ~~If a parent has no child items and goes through the full recalc app button, the rollup field is not properly reset~~
* If a parent has no child items and goes through the full recalc app, the rollup field is not properly reset

Reported by @solo-1234 on #141 - 

> Aside from that, I am seeing some issues when editing child records so they no longer meet criteria. The rollup which just looks at the child record for criteria recalculates, but the rollup which has the additional criteria on Contact does not recalculate down. Clicking the button to manually recalculate doesn't help but if I manually adjust the field to the proper number, and then click recalc, it stays at the correct number.

> Another issue I saw is with 2 records where the contact matches the criteria, but the child does not. When I edit both children at once to meet the criteria, both rollups should say 2, but the one that filters on the contact field only says 1. Clicking the recalc button fixed that.

**Comment by solo-1234** [comment]
Thanks! I think (hope) those two situations, plus waiting an extra second or two to refresh the page, should cover all the discrepancies I was seeing.

**Comment by jamessimone** [comment]
@solo-1234 no problem. My work on this will be included in the next version, as I already had quite a few things built up for `v1.2.39`

**Comment by jamessimone** [comment]
@solo-1234 I had intended to have this fixed in the next release, but wasn't able to get started beyond reproducing the first bullet point (and including the flow that reproduces that issue in the repository). I will continue to chip away at this!

**Comment by solo-1234** [comment]
No worries, thanks for the update!

**Comment by jamessimone** [comment]
@solo-1234 I have this fixed for the parent recalc button. Hoping to have it solved for the app route as well this weekend.

**Comment by solo-1234** [comment]
That's great news! Let me know once it's all updated and I'll give it a spin.

**Comment by jamessimone** [comment]
@solo-1234 I've released changes that I hope will address these issues for you with #162 - please let me know!
