### ISSUE TITLE
Correct value calculated, then overwritten in the same execution of RollupFullBatchRecalculator

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#155]
Not entirely sure if this is already explained #149 (if it is please enlighten me on what I missed!) however, we were facing an issue in the REFRESH Context, fired via Scheduled Flow.

When running the Rollup via Invocable (having made sure the correct data was queried first), we received one update too many on the Parent.

Basically went like this, looking at the history:
Wrong Value -> Correct Value
Correct Value -> Back to the same Wrong Value from before.

This happened for both Rollups the Object is used with.
It's hard to reproduce, but maybe, just maybe there is already an explanation for it to avoid it in the first place.
Right now we are able to get the correct values, having played around with Debugging the Flow several times and playing around with Rollup Control, but no actually substantial changes have been done.

Settings were:
- Queueable / Batchable as Execution Mode
- Variable Batch start size (mostly an amount that actually triggers a batch calculation in this particular case, though)
- Two Rollups, Invocation via "Rollup__mdt" based Rollups
- SObject queried, put into collection, and collection used as Flow Input.

![image](https://user-images.githubusercontent.com/34553908/131015585-d1f80d37-1468-4925-9f72-fdfd1776be9b.png)

I was expecitng one run of RollupAsyncProcessor to finish within its own log, so as to not update the same value twice, but it seems like that's not the way the Processor runs in this case?

**Comment by dschibster** [comment]
![image](https://user-images.githubusercontent.com/34553908/131215015-fe5f33fd-a983-40a9-8785-08db11257ca2.png)
Org Defaults. I only switched Batch Threshold and Standard Calculation Method Values here while trying to fix this

![image](https://user-images.githubusercontent.com/34553908/131215107-90f01522-778c-4f8f-87fb-cf0783135a9d.png)

![image](https://user-images.githubusercontent.com/34553908/131215205-f6b6dd29-bf2c-4998-8849-e0f00913091e.png)

This constellation now works, but without having changed much of anything it did not before ...

**Comment by jamessimone** [comment]
Yup, Is Full Record Set was an option for indicating that in a partial recalculation operation (and most are that way by default), the full list had actually been passed in; essentially, it was an override for scheduled flow users before I introduced REFRESH to conclusively retrieve the full record set.

you would need to set a debug trace on the Automated Process User to see the calculation log, but it’s fine if that’s too much to ask; I should have enough info based on what you’ve said. Keep me updated if any additional information comes to light!

**Comment by dschibster** [comment]
I did have a Flag on Automated Process, but I do not know if I can find the logs that appeared with the error. I'll be on the lookout!

**Comment by jamessimone** [comment]
@dschibster added some additional logging and a small change that may help with this issue. In general, I think the issue is caused by a full recalculation getting re-queued with only a subset of the calculation items (which in and of itself is a mistake, given that the full recalculation has already taken place), so in addition to tweaking how items are being considered when re-queueing (which hopefully fixes the issue), I've also added in an additional logging statement so that we can get more insight into the nature of rollups getting re-queued.

**Comment by dschibster** [comment]
That sounds like exactly what happened if I were to try and understand the logs. Thank you!

**Comment by dschibster** [comment]
@jamessimone On the topic of triggering a full recalculation with "REFRESH" always. I was trying to achieve just that at the very start, but it does require the record set to be handed over in the Apex Action, correct? That was one of the first things I tried, because semantically I would assume REFRESH would get all records anyway. Or does one Record suffice?

**Comment by jamessimone** [comment]
REFRESH does a full recalc for all parents that have child records included in what gets passed to the action.
