### ISSUE TITLE
RollupFlowBulkProcessor treats unincluded "Rollup to Ultimate Parent" as false, not as null

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#158]
How to reproduce:

- Create a Rollup from one child to the direct parent
- Check "Rollup to Ultimate Parent" on the Metadata Type, give a Field Reference to a Parent field on the very same Object
- Let run via Scheduled Flow (RollupFlowBulkProcessor, REFRESH context), only include context and records to rollup
- An error should appear:
`An Apex error occurred: System.IllegalArgumentException: Rollup To Ultimate Parent and Ultimate Parent Lookup must both be set for hierarchical rollups`
This happens because of Rollup.enforceValidationRules, where for the "Ultimate Parent" Rollup, the checkbox is actually false while the Lookup Field is populated.

Workaround:
Include "Rollup to Ultimate Parent", but leave the input empty. This seems to evaluate to null.

... Might be a flow-specific thing. If not fixable, it's perhaps best to mention it in the readme, because I ran into this issue trying to execute two Rollups to direct parents and one to a parent one hierarchy above. Thought at first it misevaluated one of the basic Rollups, but it actually didn't.

**Comment by jamessimone** [comment]
@dschibster thanks for submitting this - I'll release the fix for this in the next version
