### ISSUE TITLE
Request for multi-character delimiters for concatenation

### ISSUE THREAD

**Issue by systemsfixer** [jamessimone/apex-rollup#164]
Example use cases for multi-character delimiter: 

Creating a bullet point list of child records on a parent contact rich text field to be used in a Pardot email. This would involve using a BR() and * delimiter together.

**Comment by jamessimone** [comment]
@systemsfixer absolutely. I can include this update in the upcoming `v1.3.2` version - to be released later today, most likely. I was just looking for a compelling reason for this one!

**Comment by jamessimone** [comment]
@systemsfixer you should be all set with the latest release! Happy delimiting!
