### ISSUE TITLE
SOQL "value IN (List of Literals)" evaluates to "=" in RollupFullBatchCalculator 

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#165]
Steps to reproduce:
- Create a SUM Rollup Record with basically any Calc Item / Parent Object configuration
- In the WHERE condition, use the following semantics: `Picklist_Field_1__c = 'Literal Value' AND Picklist_Field_2__c IN ('Literal Value 1','Literal Value 2', 'Literal Value 3')`
- Run CMDT-Based Rollup via the Rollup App. Error Message will be : `Expecting a colon, found '('`
- A look a the query via debug revelas the following syntax in parsing: `Picklist_Field_1__c = 'Literal Value' AND Picklist_Field_2__c = ('Literal Value 1','Literal Value 2', 'Literal Value 3')`

It seems to me like this is the cause of the issue. The workaround would be to rephrase the where condition to a chain of OR conditions.

Am I missing something or is this currently not supported and I haven't seen it?

**Comment by dschibster** [comment]
Just confirmed that the semantics in my workaround do in fact trigger the calculation correctly.

**Comment by jamessimone** [comment]
@dschibster nice find. I do have examples of lists working so I have to hunt down what specifically about this syntax is breaking. Thanks for submitting this one, should be a pretty simple fix. Happy there's a workaround for now though.

**Comment by jamessimone** [comment]
@dschibster just pushed up a fix for this - I'll be looking to release this later today.

**Comment by jamessimone** [comment]
@dschibster you should be all set with the updated version - thanks!

**Comment by dschibster** [comment]
Thanks for the quick reaction!
