### ISSUE TITLE
Re-parenting a child in a grandparent rollup

### ISSUE THREAD

**Issue by rygramer** [jamessimone/apex-rollup#179]
@jamessimone when I re-parent a child in a grandparent rollup configuration, the **original** grandparent isn't be **decremented** and the **new** grandparent isn't being **incremented**.

Original Grandparent - `a2978000000Gmc0AAC`
New Grandparent - `a2978000000Gmc5AAC`
Log - [apex-07L780000008vgJEAQ.log](https://github.com/jamessimone/apex-rollup/files/7247309/apex-07L780000008vgJEAQ.log)

**Comment by jamessimone** [comment]
Très intéressant - we [have tests for this specific situation](https://github.com/jamessimone/apex-rollup/blob/main/extra-tests/classes/RollupIntegrationTests.cls#L587), so I'm very surprised to hear that. I'll have to take a look through at the log to see what's going on - perhaps something will jump out at me. I'll keep you updated!

**Comment by rygramer** [comment]
This is what I'm trying to do -- 

`upsert new RollupSettings__c(IsEnabled__c = true);` in TestSetup, of course. 😉

```
@isTest
    public static void shouldRecalcRollupToGrandparentWhenChildIsReparented(){
        test.startTest();

        Grandparent__c gp1 = new Grandparent__c(
            AmountfromChildren__c = 0
        );
        insert gp1;

        Grandparent__c gp2 = new Grandparent__c(
            AmountfromChildren__c = 0
        );
        insert gp2;
        
        Parent__c p1 = new Parent__c(
        	Grandparent__c = gp1.Id
        );
        insert p1;

        Parent__c p2 = new Parent__c(
        	Grandparent__c = gp2.Id
        );
        insert p2;
        
        Child__c c = new Child__c(
            Parent__c = p1.Id,
            Amount__c = 5.00
        );
        insert c;

        c.Parent__c = p2.Id;
        update c;

        test.stopTest();

        c = [SELECT Parent__r.Grandparent__c FROM Child__c WHERE Id = :c.Id];
        system.assertEquals(gp2.Id, c.Parent__r.Grandparent__c); // PASSES

        gp1 = [SELECT AmountfromChildren__c FROM GrandParent__c WHERE Id = :gp1.Id];
        system.assertEquals(0, gp1.AmountfromChildren__c); // FAILS - actual is 5

        gp2 = [SELECT AmountfromChildren__c FROM GrandParent__c WHERE Id = :gp2.Id];
        system.assertEquals(c.Amount__c, gp2.AmountfromChildren__c); // FAILS - actual is 0

    }
```

**Comment by jamessimone** [comment]
@rygramer are you sure the log that you attached is from this test run? In looking through the log, I am seeing a lot of mismatched values: the Child__c, for example, is reporting an Amount__c of 10 - and the GrandParent__c's AmountfromChildren__c is reporting a pre-existing value of 25, which doesn't seem to resemble the test method that you've pasted above.

**Comment by rygramer** [comment]
@jamessimone sorry for confusion. No, the first debug log is from a live run (before I figured out how to write a working test class).

Here's the test class I'm running (slight modification from the above in terms of what's printed and asserted) --
[RollupTest.txt](https://github.com/jamessimone/apex-rollup/files/7260044/RollupTest.txt)

And the log from test 2 `shouldRecalcRollupToGrandparentWhenChildIsReparented` --
[07L780000008wBwEAI.log](https://github.com/jamessimone/apex-rollup/files/7260050/07L780000008wBwEAI.log)
(I couldn't figure out how to adjust logging levels in VSCode, so that log is the whole entire thing, sorry about that.)

**Comment by jamessimone** [comment]
@rygramer don't worry at all - believe me when I say, I'm quite used to looking at the full log these days! Formatting logs is also a pain, I wouldn't waste time on it. Thanks for sending that along, I'll take a look!

**Comment by jamessimone** [comment]
@rygramer should have that all patched up. I am going to be taking a look at a few more things here, this afternoon, but I'll probably shoot to release the new version today/tomorrow. Thanks for your help with this!

**Comment by rygramer** [comment]
🙌 happy Friday good sir

**Comment by jamessimone** [comment]
@rygramer my apologies as well - I _will_ get to this one, just been a bit slower than I would have liked

**Comment by rygramer** [comment]
Take your time man! No rush at all

**Comment by jamessimone** [comment]
@rygramer picking this one back up after a hiatus (for which I apologize). I'll be looking through the log you attached, but in the meantime I want to jot down some general thoughts/suspicions:

* full recalc rollups are always sorted to the end of any given list of rollups
* first log entry is a `RollupParentResetProcessor` - could be wiping out legitimately calculated reparented values after the fact, given the above

**Comment by rygramer** [comment]
No rush man, I ended up going a different route for the implementation so not actively using grandparent roll ups in production.

Parent roll ups still working great. I abandoned flow / invocable method in favor of a trigger based approach. Paired with your `andFinally()` lightweight trigger handler, it feels like the superior implementation.

Great work as always.

**Comment by jamessimone** [comment]
@rygramer finally got this one figured out - I know that you ended up taking a different approach but once this is released in `v1.3.20`, I'd love it (if possible) for you to re-run the test that you had shown me above to double-check this is working properly. Thanks so much!

**Comment by rygramer** [comment]
Will do this weekend!

**Comment by rygramer** [comment]
@jamessimone still seeing a test failure. Maybe I have something misconfigured?

Here's my sfdx project - https://github.com/rygramer/apexRollupTests

If you run `sh scripts/Initial_Deploy.sh`, it'll spin up a scratch org and install `Apex Rollup`

**Comment by jamessimone** [comment]
@rygramer I will take a look - thanks so much for the minimal repro!

**Comment by rygramer** [comment]
@jamessimone No rush at all on this

**Comment by jamessimone** [comment]
Thanks Ryan - I was able to take a look through yesterday and this morning for a bit and have a fix prepared. I still have one of my existing reparenting grandparent tests that is failing, but once I'm able to address that and clean things up I'll look to release the _actual_ fix for this. I really appreciate you putting a full repro together; I can't tell you how much time that saved me, so thank you again!

**Comment by rygramer** [comment]
Sorry it took me so long to think to do that. TBH, I've learned a lot about scratch orgs since I first raised this in September. Thanks for taking a look dude!
