### ISSUE TITLE
Using OR within Calc Item Where Clause

### ISSUE THREAD

**Issue by AndyHaas** [jamessimone/apex-rollup#181]
Getting an error when using OR within my SOQL clause. Here is the log info and other details

12:38:33.0 (79875342)|VARIABLE_ASSIGNMENT|[15]|this|{"statefulLookupToCalcItems":"0x6bb77ed9","objIds":"0x49c3e79c","previouslyResetParents":"0x5168c2c8","queryString":"SELECT Id,porelite__TOTL__c,AccountId,porelite__STAT__c\nFROM Opportunity\nWHERE Id != :objIds\nAND porelite__STAT__c = 'Closed' OR porelite__STAT__c = 'Completed'\nORDER BY AccountId","recordIds":"0x2a7770dd","rollupInfo":"0x7cde9d08","calcItemType":"common.apex.runtime.impl.ApexSObjectTypeToken@1d4e514b","isProcessed":false,"overridesRunCalc":false,"stackDepth":0,"calcItemReplacer":"0x5bd7ce38","invokePoint":"0x7ae5276c","isCDCUpdate":false,"isConductor":true,"isFullRecalc":true,"isNoOp":false,"oldCalcItems":"0x3b3dec82","queryCount":-1,"rollupControl":"0x788c07f3","rollups":"0x75cc3d8c"}|0x2b511f02

12:38:33.0 (80349231)|EXCEPTION_THROWN|[19]|System.QueryException: unexpected token: OR

I can run this in the developer console with no issues.

**Comment by jamessimone** [comment]
@AndyHaas thanks for submitting this issue - I have a fix for this in the works, it will be part of the forthcoming `v1.3.8` (which I am hoping to release later today). Apologies for this, in the meantime.
