### ISSUE TITLE
NullPointer in RollupFullBatchRecalculator - Failed to re-queue after Rollup fires in Trigger once?

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#193]
Hi there,

The Rollup I want to calculate in #190 is starting to act up again - but maybe this is just the configuration. I have to say I tried several ways of going about firing this Rollup so far:

* Bulkified Scheduled Flow: String overflow. :(
* Scheduled Flow with Batch Option: Query the Parent Object, make an [where parent in :list] Query, perform rollup on those - That didn't seem to fire anything, although I explicitly set Deferred to True and fired "Process Deferred Rollups" after it. -> Maybe I am doing something wrong here, if this is something you haven't encountered yet I would also gladly make an issue for it.
* Now the third option I tried is the Rollup App, just to get the values on there for once. -> I am here now

However, after the Batch Job starts, all I receive is NullPointerExceptions out of nowhere, because the Job seemingly doesn't find anything when running getAsyncRollups(). It also says that canEnqueue is false, because of an Async Job having run already. Can that be the previous instance of Rollup running on the parent Object?

```
14:04:22.229 (25710794243)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.RollupAsyncProcessor.processDeferredRollups: line 669, column 1
Class.RollupAsyncProcessor.process: line 565, column 1
Class.RollupAsyncProcessor.runCalc: line 281, column 1
Class.RollupFullBatchRecalculator.execute: line 31, column 1
```

Attached is the Log I got from it. 
[full recalc chunk log.txt](https://github.com/jamessimone/apex-rollup/files/7373122/full.recalc.chunk.log.txt)

**Comment by dschibster** [comment]
Interestingly enough, a few batches have seemed to slip through the cracks when I decreased the chunk size to 200. Does that ring any possible bells? What would happen if there is a bunch of no-ops sprinkled throughout the chunks?

**Comment by dschibster** [comment]
@jamessimone 
I've actually today gotten a few Developer Script exceptions on Production that reference the same line (package version was 1.3.1, but I recognize the line because it's the exact same as here).

A record of an Object that had Rollup running as part of the Trigger Pattern, but didn't have any Rollup records, suddenly started failling on me because of an NPE at the exact same location.

While I wager that it could still have something to do with AVG calculation, how can we explain non-rollup objects running through the method and getting into runCalc() giving out NullPointers?

**Comment by jamessimone** [comment]
@dschibster I am looking to release at least the initial update for this today/tomorrow. I am also still looking into the _result_ of the full recalc occasionally being off when using the full batch recalculator, though I may need to open another issue to represent that specific issue since I'll be closing this one out. 

Apologies for the delay, I spent quite a bit of time on #204 over the weekend, hardening the approach there.

**Comment by dschibster** [comment]
@jamessimone It's all good, I wanted to say this because it actually happened outside of a full recalc. That was a batch job on an object that should only check for rollups but not execute them.

**Comment by jamessimone** [comment]
@dschibster interesting indeed! Any chance you have a log for that? Especially for trigger-related code, rollup should early abort if there’s no matching metadata, but clearly there’s some edge case here.

**Comment by jamessimone** [comment]
@dschibster for that last NPE, are you invoking rollup via `runFromTrigger();` ? I am going to put an extra fail-safe in.

**Comment by dschibster** [comment]
Yep, that is via `runFromTrigger`. Unfortunately don't have a detailed log, only the Apex Developer Exception Email. :/

**Comment by jamessimone** [comment]
@dschibster lots of improvements coming. Hoping to finish up this version today - I would expect this error to go away for good.

**Comment by jamessimone** [comment]
This should be addressed with #206

**Comment by dschibster** [comment]
@jamessimone Can confirm that the full recalc doesn't throw me any error anymore! I did have a hiccup where one Batch Job seemed to have been running a little too long on one Batch - But reducing the Batch Size solved that without any negative consequences.

**Comment by jamessimone** [comment]
Awesome. Glad to hear it!
