### ISSUE TITLE
Add CMDT option for use of custom delimiter with concat and concat distinct operations

### ISSUE THREAD

**Issue by jamessimone** [jamessimone/apex-rollup#2]
Right now, Rollup defaults to comma-separated for concat operations, but users should have the option to use the delimiter of their choice (via @solo-1234)

**Comment by ssk42** [comment]
Now that it can take on MSPs, shouldn't Rollups also allow to easily use semicolons too?

**Comment by jamessimone** [comment]
@ssk42 haha I think I had a dream that I had closed this issue, and seeing your comment in my inbox led me to immediately think “he must be trolling me to be commenting on this closed issue.”

I will _consider_ unleashing semi-colon delimited madness unto the world, since it seems to bring at least you (and potentially @solo-1234) minuscule iotas of happiness.
