### ISSUE TITLE
Full Recalc Rollups to listen for the Chunk Size in their Rollup Control Record

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#203]
Hi there @jamessimone  
Not an urgent one because it's easily controllable in Org_Defaults, but I noticed that by assigning a non-default Rollup Control to a Rollup and then performing a full recalc (either from LWC or Flow) results in the Default being taken - which may be higher on purpose because only certain Objects have a higher load on the system.

It seems like the sensible default is retrieved as a singleton when there is no sync call to a Rollup, correct? It seems to me like it would be core functionality that we are touching here, so I'd rather not work on that unless it's actually unintended behavior, and even then I'd have to comb my way through Rollup construction before anything else. :-)

**Comment by dschibster** [comment]
Hi @jamessimone  I tested this with the CMDT based Full Recalc Action, and despite being on 1.3.10, the only Control that is regarded is Org_Defaults. I have selected two Rollups (separately) each with their own Control ("BatchJobManaged"), where I set a Chunk size of 250. Instead it decided to hop up to 2000 (like in Defaults) anyway. Is that use case not entirely covered?

**Comment by jamessimone** [comment]
@dschibster I did not expect that, at all. I’ll have another look through.

**Comment by jamessimone** [comment]
@dschibster of course there _was_ one situation - full recalcs - where the updates were not being respected, which explains why your test of that functionality didn't work. I just pushed the fix for this. I am hoping to get `v1.3.11` out there in the next day or so.

**Comment by dschibster** [comment]
Thanks so much!

**Comment by dschibster** [comment]
Working now, thanks a bunch!
