### ISSUE TITLE
Parent field filter - Null Pointer Exception when filtered field belongs to a relationship other than the parent where the rollup value is

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#204]
Hi! I am working on a few rollups that filter on regular fields and also on parent/lookup fields. When I try changing a parent record so that it's filtering field is blank, I get a NullPointerException. Editing this record triggers a flow which fetches some records of the other parent (the one I'm rolling up to) and does a "refresh" rollup starting from the parents.

Any ideas? Thanks!

**Comment by solo-1234** [comment]
Hi! Now I'm getting a new error...

```
Class.RollupEvaluator.WhereFieldCondition.getRelationshipFieldValue: line 691, column 1
Class.RollupEvaluator.WhereFieldCondition.getFieldValue: line 673, column 1
Class.RollupEvaluator.WhereFieldCondition.equals: line 596, column 1
Class.RollupEvaluator.AndConditionalGrouping.conditionallyEquals: line 543, column 1
Class.RollupEvaluator.ConditionalGrouping.equals: line 501, column 1
Class.RollupEvaluator.WhereFieldEvaluator.innerMatches: line 249, column 1
Class.RollupEvaluator.WhereFieldEvaluator.matches: line 241, column 1
Class.Rollup.getFullRecalcQueryWrapper: line 1747, column 1
Class.Rollup.processCustomMetadata: line 1689, column 1
Class.Rollup.performRollup: line 627, column 1
Class.RollupFlowBulkProcessor.addRollup: line 127, column 1
13:57:27.534 (1717121527)|FATAL_ERROR|System.SObjectException: Invalid field FieldName__c for RollupParent__c
```

FieldName__c is the filtering field on the parent, and RollupParent__c is the OTHER parent (the one I'm rolling up to).

Can it be putting the wrong object name in the soql where clause?

**Comment by solo-1234** [comment]
Update - I modified my flow to run the rollup from the children instead of from the parent, and now I don't get the error anymore. So it must be unique to when rollup is started from parent.

**Comment by jamessimone** [comment]
@solo-1234 interesting - let me take a look through that section again, I have a test for this but I think it's only testing when the parent-level field is on the parent you're rolling up to. As you said, that's something specific to when the rollup starts from the parent, but I can get this addressed for sure.

**Comment by solo-1234** [comment]
Hmmm... since the original issue is fixed, and I switched my rollups to start from the child, it looks like it's not recalculating when I change a filtering field value on the parent anymore. Could that be possible?

**Comment by jamessimone** [comment]
Ah. Yeah. Hmm ... that's a tricky one. Now that the rollup is technically triggered from the child, there's nothing happening when the parent gets updated to not align. The same would be true if the rollup started from the parent, for the record; a change to a field that was being filtered on which only belonged to the child would fail to get picked up at the moment of that update.

I think I need to revise the Readme section for this, since if you're filtering on parent fields you technically need two rollups set up - one for the parent, one for the child. I also have to fix the stacktrace that you sent me, above.

**Comment by solo-1234** [comment]
So I have these rollups called from two separate flows - one from the child that runs on UPDATE context, and one from the parent (not the rollup parent, the other parent) that fetches the child records and then passes them to the rollup action in REFRESH context. So one set of rollups stored in CMDT, called by two flows, so that we handle all the edits that require re-rolling up.

That's why I'd think this should work!

**Comment by jamessimone** [comment]
Ah yeah. That _should_ work, yes. Let me investigate ....
