### ISSUE TITLE
Getting test errors after upgrading to the newest version

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#205]
Hi! I recently upgraded to the newest version and now I'm getting test errors in my org:

Screenshots:
![image](https://user-images.githubusercontent.com/59446952/139468427-ab9e6a4d-3de6-4dea-82f5-2848a463fd2c.png)
![image](https://user-images.githubusercontent.com/59446952/139468476-ff10890b-6f5e-4750-8bf9-58b57c89c2c5.png)

**Comment by solo-1234** [comment]
I deleted the two classes that were failing, and now all is well. Thanks!

**Comment by jamessimone** [comment]
Wonderful. Thank _you_!

**Comment by jamessimone** [comment]
@solo-1234 sorry, also just now seeing your question (which I somehow missed previously, so apologies twice for that!) - yes, I would delete all the rollup test classes, they are no longer being maintained in terms of what gets deployed (but you can visit the repo if you miss them and like to see them in their current forms at any time 😁!)

**Comment by solo-1234** [comment]
Got it! Will the lack of test classes affect my org's code coverage percent?

**Comment by jamessimone** [comment]
No, it will not (assuming you are installing via the unlocked package) affect your org’s code coverage

**Comment by solo-1234** [comment]
Thank you!
