### ISSUE TITLE
Production Package not promoted yet

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#207]
Hi James,

![image](https://user-images.githubusercontent.com/34553908/140280944-b0351126-8383-4349-8026-d0fea93299ca.png)

Seems like the package hiding behind the Install in Production Button is not yet promoted.  Mind taking care of that? 😄

**Comment by jamessimone** [comment]
Interesting … my build script in GitHub Actions is supposed to promote the package automatically. I will promote in just a few minutes, apologies!

**Comment by jamessimone** [comment]
All set!
