### ISSUE TITLE
Mass edit records to not meet criteria - rollups are just reduced by 1

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#208]
Hi! I think I just found another bug...

When I mass edit 3 records to make them no longer meet criteria for rollups, the rollups are decreased by 1 instead of by 3. Same deal if I edit them to now meet criteria.

The specific situation is record-edit flow that adds both record and record__prior to record collection vars, and then passes both collections to the CMDT rollup action.

TIA!

**Comment by jamessimone** [comment]
@solo-1234 is this a count rollup? Count distinct? I haven't tested mass-edit (outside of Apex), so I'm wondering if the issue isn't in how the save is being performed (IE is it truly bulkified, or are the saves happening one at a time, and possibly in such a quick succession that only the last save truly "takes"). So let me look into this and get back to you, and in the meantime if you could follow up with what kind of rollup you're performing, that would be great!

**Comment by solo-1234** [comment]
It's count, not distinct. The mass edit is done using SOQLDatatable embedded in a flexipage, I would assume that it's truly bulkified.

Thanks for your help!

**Comment by jamessimone** [comment]
Ahh, SOQL datatable does an update per row. This might be ... a fascinating solve. That's great info though, thank you!

**Comment by solo-1234** [comment]
Ohhhh interesting! I didn't realize that!

**Comment by jamessimone** [comment]
it's a conscious choice on @tsalb's part - the existing Lightning Data System (LDS) features exposed for LWCs making updates to records doesn't have a bulk option, but he's aligned to the platform's exposed capabilities on this front. There may be some bulkification that happens, but it's not a guaranteed thing. I have SOQLDatatable installed, as well, so it should be relatively simple to drum up an example of how the updates are interacting with rollup!

**Comment by solo-1234** [comment]
Very interesting - thank you for investigating this!
