### ISSUE TITLE
Records with parent-level where clauses in Rollup.runFromTrigger run into FinalException since 1.3.9

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#209]
Hi @jamessimone, here's one we ran into in Production after upgrading the package version some.

I installed 1.3.10 yesterday and one Object (actually currently still the only Object actually part of `Rollup__mdt` records on Prod) were unable to get updated. 

![image](https://user-images.githubusercontent.com/34553908/140488587-90a52dce-7f42-4dbd-8e4b-c58358f758c6.png)

We received a `System.FinalException: Record is read-only` exception during Parent Record re-writing like the record complained about being edited in an after-update context.

This problem went away once I downgraded to 1.3.8, so this issue exists since 1.3.9. Do you have any clue? The record itself is definitely editable.

Removing my parent-level where clause solved the issue

------------
Some more info.

* `Replace Calc Items Async When Over Count` was set to 1
* One of four `Rollup__mdt` records had a Parent-Level WHERE Clause
* The Rollup was fired through `runFromTrigger()`
* I would have expected this to run through, instead it went into the `FinalException` as described
* Reducing `Replace Calc Items Async When Over Count` to 0 and keeping the parent-level clause also results in the aforementioned Exception

**Comment by jamessimone** [comment]
@dschibster ah. yes. OK, this error makes sense. As part of the change to `1.3.9`, I went to modifying the collections in place of replacing them - this is to support multiple rollups having parent-level where clauses at any one given time.

I actually ran into this same error in a slightly different context yesterday while debugging another issue, and I'm curious - would it be possible for you to try modifying the following lines in `Rollup.cls`:

```java
  private static List<SObject> getTriggerRecords() {
    if (records != null) {
      return records;
    }

    return Trigger.isDelete ? Trigger.old.clone() : Trigger.new.clone();
  }
```

Note the additions of the `clone()` calls there - I think that would solve the problem. I am going to be wrapping up a few other things today and hopefully will get to being able to add a test for this one, as well.

**Comment by dschibster** [comment]
I can try that next week surely. That is in order to stop the reference from being protected by Trigger Context right?

**Comment by jamessimone** [comment]
yup, the trigger records are final collections - in this case, we're not actually looking to update the records anywhere beyond their in-memory representations so that they'll have the parent object references correctly set, but Apex doesn't know that!

**Comment by dschibster** [comment]
Still getting a read-only Exception unfortunately, I like the thought process though, I would have tried the same thing.

**Comment by jamessimone** [comment]
Hmm, the method above it for old records may also have to be modified to do the same thing. I am doing a bunch of work on the next version today and will definitely get this fixed up.
