### ISSUE TITLE
Full Recalculations leave some fields wrong / empty

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#210]
Hi @jamessimone 

Jotting this down as an issue but I also have a question regarding the functionality hoping that we can solve this together.
The Object I am currently try to roll up to (using both AVG and MAX in two separate fields) seems to be running into incomplete data despite running Full Recalcs on a Daily basis. 

I am firing each of the recalculations separately currently.

There's a few instances of the following issues coming up:

* Fields not being filled at all
* AVG and MAX being the same field despite there being different amounts that would influence the AVG

Now the first question I had was if that can be influenced by the Chunk size: Assuming that only a smaller amount of records is on one side of one chunk, and then another chunk contains data for the same parent record, what would normally happen at that point?

Second question: How would that explain some fields being empty?

Unable to provide logs currently, but for example for one of the specimens with a missing field, simply hitting the "Recalculate Rollups" LWC Button handed me the field value I was missing, so it was definitely not wrongly configured.

EDIT:

Even after Rerunning with Chunk Size 1000, there's still some examples that didn't get calculated correctly:
![image](https://user-images.githubusercontent.com/34553908/140539632-934d6b18-8563-4b6a-941b-07bb40793baa.png)

![image](https://user-images.githubusercontent.com/34553908/140539710-9b3edcdd-88ca-4a4b-9ed8-3262cfea3a88.png)

The MAX is correct but the value above should have been 85. It looks to me like this one didn't even get picked up?

**Comment by jamessimone** [comment]
Hey @dschibster - I suspect the chunk size does factor into this issue (and I found this while investigating #203 for you), although rollup does attempt to handle this situation already - this is why `RollupFullBatchRecalculator` implements `Database.Stateful` - it attempts to manage internally all of the children for the given parent records in question so that even if they fall into two separate batches, they parent's values are only full recalculated once.

This has proven a tricky issue to test for given the limitations on multiple batch chunks/re-queueing within a test context, and it seems the original solution that I put in place has slightly missed the mark. I fully intend to investigate and fix this issue (potentially in conjunction with a scripted recalculation that I can run through an Apex script as part of my pipeline to verify the correct results, since I can't _really_ do this in a test context properly).

**Comment by dschibster** [comment]
I fully understand. The only thing that makes me curious is there being complete skips - these don't make much sense to me in any way.

**Comment by jamessimone** [comment]
@dschibster I was able to take some time this morning to step through this one, and I believe I've come to the root of the issue for both problems. The logic that I had to reference the cached (stateful) version of the previously retrieved calc items for any given parent record was _slightly_ flawed, and in manual testing I was able to quickly reproduce the issue and ... hopefully address it.

**Comment by dschibster** [comment]
@jamessimone  I come with news, both good and bad!

1. My Recalcs are working pretty well so far right now!
2. Averages are still not being calculated correctly.

I think by now this is probably specific to averages, not to the Full Recalculation. Max values were correct in all instances I checked, but I still get either empty or non-updated wrong field values in the second Rollup. I tried it both with two Rollups running at once (MAX, AVG) and both of them running separately. Batch Sizes I tried were 250 and 1000. One Rollup calculated itself to death in Batch Size 2000 x).

**Comment by jamessimone** [comment]
@dschibster ok let me change my manual testing to average and see what the deal is there. It feels good to make progress on this one!

**Comment by jamessimone** [comment]
@dschibster I started looking into the issue with average this morning, but so far I haven't been successful in tracking down the problem. The only thing that I've seen thus far is that it's possible for a deferred rollup _and_ another iteration of the full batch recalculator (when the batch size is small enough for multiple calc items to share parents between batches) to both update the same parent record - I could put in an optimization to prevent this double-update, but the calculation done in both cases was correct, and it would probably be more hassle than it's worth to put the optimization in place.

As I said, I'll keep digging - any further info from you would be much appreciated though!

**Comment by jamessimone** [comment]
@dschibster that should be plenty of info - know that I appreciate the time it took for you to write that up!

**Comment by dschibster** [comment]
Anything that helps you help us succeed with the app. :)

**Comment by dschibster** [comment]
Just wondering if you have any update in the interim @jamessimone. Were you able to find any issue with my setup?

**Comment by dschibster** [comment]
Just a thought that came to mind, just trying to get one contract that I found while checking the Nebula Logger Log Stream. Some records of the junction Object simply are not picked up in the full recalc. I have run it several times by now, switching from WHERE Conditions on the Parent field, to the formula field, to only checking the one Id (which lead to DeferredFullRecalc, not my aim). 
When clicking the button for Rollup Recalc on the Parent, and everytime it's selectively chosen, it works. In the Batch Job, the record seems to simply get ignored. The Log Stream does not pick up any Logs with the Parent Id I chose to check. Just maybe this is also the reason some Rollups are wrongly calculated? The records are simply not picked up by either Rollup itself or the Batch Job?

Food for thought, @jamessimone

**Comment by jamessimone** [comment]
@dschibster thanks for this additional context. I haven’t been trying with a where clause, so perhaps that’s where the issue lies. I did do some investigation on this issue this weekend, and while I didn’t find anything that seemed directly related to your issue, I did some tangentially related work on the AVERAGE full recalcs.

For the records that are not picked up - and it sounds like it’s the same ones omitted each time - is there anything that they have in common?

**Comment by dschibster** [comment]
Unfortunately, not really anything that springs to mind. Especially in the context of the Rollup record they should definitely all be the same. As it's a Junction Object, it's pretty uneventful in terms of proprietary data.

**Comment by dschibster** [comment]
Actually, nevermind, one of my test subjects does not seem to come up in a regular SOQL either. I'll dig deeper on my end.

**Comment by jamessimone** [comment]
Oooh! Very interesting indeed. I will stay tuned

**Comment by dschibster** [comment]
@jamessimone My Full Text Search failed me. In a CSV I did find the records in regular SOQL. That brings me back to square one. Additionally even removing the filter does not deliver these results. Hark.

**Comment by dschibster** [comment]
The Query Count is correct. I am not finding a Nebula Log Entry for one of the failed parents though.

**Comment by jamessimone** [comment]
@dschibster added in some additional optimizations that ... _maybe_ ? ... will help with the issues you've been describing. I apologize - I know this has been a hard one to pin down, but I will keep working on it with you till we have things 100% bulletproof.

**Comment by dschibster** [comment]
@jamessimone Thanks for that. I installed the latest version but it doesn't seem to be picking up the ones that weren't picked up before anyway. It's so strange because I can't seem to find any kind of regularity in there. It just doesn't include them in the RollupAsyncProcessor **anywhere** - although they are actually queried as part of the full batch calculation.

**Comment by jamessimone** [comment]
At this point I have to believe it’s some kind of bug with the SOQL where clause, unless you’re saying they aren’t included if you have no clause.

**Comment by dschibster** [comment]
I thought I tried that and didn't get a result, I will check again. I did strangely enough get an update from my Automated Process User at a time where I wasn't even close to running a Rollup, so that was something. I reset the value again and will watch the record more closely now.

**Comment by dschibster** [comment]
Right on, one of my problematic records (have yet to check others) now has a value. I ran the Rollup without a query. However both the Top and the Bottom Level Query (once referencing a formula, once referencing the Parent) have both not amounted to any result. Plus, I actually did receive the correct amount of records - they may have been wrongly denied processing at another point then.

**Comment by dschibster** [comment]
It seems like the data is more complete than it ever was now! So it really did seem like my records have been ignored because of the WHERE clause. @jamessimone

**Comment by dschibster** [comment]
@jamessimone Question: Does RollupAsyncProcessor check WHERE Conditions even after the Record has been picked up by a Full Recalc?

**Comment by jamessimone** [comment]
Yes, it does. This is necessary for a number of reasons, one being that I didn’t feel good about concatenating where clauses for bulk full recalcs. There are a couple of things that come to mind when it comes to what might be going on, but if there’s any info about the where clause you can share - particularly any string-based values, which have the most in the way of edge cases - I am certain we can figure this out!

**Comment by dschibster** [comment]
It's actually a string comparison, but most likely the easiest one you could do. `Formula_value__c = 'Picklist Value'`.

I tried this with both the Formula Field on the Junction Object and the original one on the Parent, the latter of which is part of many a Flow and Apex Logic, but both of them led to the same issues - the one that we have been analyzing here.

**Comment by jamessimone** [comment]
@dschibster is there anything about the picklist value in question that's unusual? For example, some prior issues we've had come up with text-based comparisons:

- they had and/or in them (which was causing the regex in `RollupEvaluator` that runs to incorrectly split them out
- they had parenthesis in them (similar to the above)
- they had the word `IN` in them (could be the same with the word `LIKE` - I legitimately don't know if I've tested that use-case out)

Once we've pinpointed what the issue is with that specific string, we can represent it in a new issue and get it patched up!

**Comment by dschibster** [comment]
The value is literally just 'Germany', is there anything curious about it?

**Comment by jamessimone** [comment]
.... no, that seems about as standard as can be.

OK, let me keep investigating this. Thanks for the info!
