### ISSUE TITLE
Attempt to de-reference a null object

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#220]
Hey James,

I'm not sure when this started, but I'm getting QueuableHandler errors when editing or deleting a record from the child object that rolls up.

I don't seem to have issues when I add a new child. It also works fine when I do a recalc from the parent or from the Rollup app, but every time I edit or delete a child, I get a de-reference error.

I have attached the log file:
[apex-07L74000000U95mEAC.log](https://github.com/jamessimone/apex-rollup/files/7671560/apex-07L74000000U95mEAC.log)

I honestly haven't been updating every release so I probably jumped a few versions in my last upgrade. I also don't know if it just started after the last time I upgraded, but it seems likely since no one reported issues until recently.

Here are my Org Defaults:

![image](https://user-images.githubusercontent.com/643517/145105954-32538a16-d09f-4375-801e-f5a2e4aa5bf4.png)

Here is my configuration:

![image](https://user-images.githubusercontent.com/643517/145106007-a3c8db5c-1f81-4e54-8a18-6ef3d1448f37.png)

The issue is when I edit or delete from the Fund Grant Association.

**Comment by jamessimone** [comment]
@jkenzer so sorry - I actually have been getting the error emails for this issue and I fixed it in commit https://github.com/jamessimone/apex-rollup/commit/21f63bea3b14f347f72704bbb4ebcd02728adb4c - I am just working to finish up the fix for #208 (or at least attempt to) prior to releasing the next version with that fix. 

Good to see you here, and I'm sorry you're experiencing this issue!

**Comment by jkenzer** [comment]
@jamessimone Thanks. Good to know you are on top of it.

I just installed Nebula to try that out. Just an FYI, it doesn't seem to log errors generated via the QueueableHandlers. Not sure if that is a limitation of Queueables.

**Comment by jamessimone** [comment]
@jkenzer you mean the [Nebula Logger Adapter plugin](../tree/main/plugins/NebulaLogger)? There is logging for that, you should be able to see errors getting logged via the `RollupFinalizer` class ...

**Comment by jamessimone** [comment]
@jkenzer please let me know if the latest release fixes this for you. Otherwise feel free to re-open; it’s been a bit busier than usual so I haven’t had as much time to test the fix out as I normally do, but rest assured if there’s any other problem we _will_ get it patched up!

**Comment by jkenzer** [comment]
@jamessimone All looks good. I haven't had an error since upgrading yesterday. I upgraded to 1.3.19 this morning as well.
