### ISSUE TITLE
Rolling up to multiple objects via text id field

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#233]
Hi! Back again with an edge case issue...

I have an object (`Charge__c`) that has a fake lookup field which is a text field, and can contain the id of one of a few different objects. I started with rollups from that child to one of the parent objects and it worked fine. When I added in another rollup to another valid parent object, I started getting errors when running the rollups. I'm running them in flow using the CMDT action. Both rollups use the text "id" field for the `Lookup Field On Calc Item`.

Here's the error:
`EXCEPTION_THROWN [800]|System.SObjectException: Parent_A__c.Total_Paid_rollup__c does not belong to SObject type Parent_B__c`

Here's the stack trace:
![image](https://user-images.githubusercontent.com/59446952/149812770-b809f33e-5b0f-4a98-8186-760cace242e2.png)

Any ideas what could be going wrong?

Thanks!

**Comment by jamessimone** [comment]
Ah that’s an interesting one! I will have to take a look, should be an easy fix. Also, hats off to you - love the multiple parent lookup solution!

**Comment by solo-1234** [comment]
Nice, thanks! And it's so satisfying to trigger all those rollups via the one apex action, no matter where they are rolling up to!

**Comment by jamessimone** [comment]
@solo-1234 is this in the most recently published version (`v1.3.23`) that you are getting this error? I ask because a fix for this should be in place - it was introduced in `v1.3.10`  and the stacktrace you've provided doesn't align with the current versions of those methods.

**Comment by solo-1234** [comment]
Ah, good point! I'm on an older version, had been waiting to work out the other kinks before upgrading my prod org. I'll upgrade it now and see what happens!

**Comment by solo-1234** [comment]
That fixed it! Many thanks!!

**Comment by jamessimone** [comment]
No problem 👯
