### ISSUE TITLE
Adding support for Description or other documentation to metadata

### ISSUE THREAD

**Issue by feisley** [jamessimone/apex-rollup#241]
We are in the process of moving from DLRS to apex-rollup and one of the items we miss is the ability to add a description or notes to the rollup. This can contain basic details as to the use case for the rollup as well as a reference to our issue tracker for the full history and details.

Any chance this would make sense as an addition to apex-rollup? Alternatively if it is not a good core feature, could we just add a custom text field to the metadata without it getting impacted by future upgrades?

**Comment by jamessimone** [comment]
@feisley I can absolutely add this to the base package. I am looking to wrap up the latest release within the day and I’ll include this in there!

**Comment by feisley** [comment]
@jamessimone awesome. 

One thing I did want to point out when I was digging into this was the potential impact of the type of text field on governor limits. 

From https://help.salesforce.com/s/articleView?id=sf.custommetadatatypes_limits.htm&type=5

"SOQL queries containing long text area fields count toward Apex governor limits."

As written this would seem to imply you can have longer text in custom metadata and calls not consume governor limits so long as you don't include that specific field.

**Comment by jamessimone** [comment]
@feisley thats correct; I won’t query for the field but have included it in the metadata and page layout!
