### ISSUE TITLE
Sort order for concatenated values

### ISSUE THREAD

**Issue by systemsfixer** [jamessimone/apex-rollup#246]
Feature Request:
Provide a mechanism to control the sorting of aggregated records for the concatenate functions. 

Current order by functionality appears to only work with FIRST and LAST functions.

**Comment by systemsfixer** [comment]
Also I noticed the wiki states multi-character delimiters are not supported but that was enhanced already.

**Comment by jamessimone** [comment]
@systemsfixer whoops good call on the wiki - I will correct that! Let's talk more about your feature request, as well - very curious to hear what you're looking for in terms of sorting options.
