### ISSUE TITLE
Rollup not running when same-object lookup nulled out

### ISSUE THREAD

**Issue by systemsfixer** [jamessimone/apex-rollup#247]
Background:
Same object rollup (counting number of child records on an immediate parent of same object), using CMDT and calling `Rollup.runFromTrigger();`.

Issue:
When child record has the lookup field cleared out, the parent record target rollup field is not decremented.

Repro:
- Create a rollup from an object to the same object.
- Fill in the lookup field and observe the rollup incrementing as expected
- Clear out the lookup and observe that the rollup does not decrement as expected

Desired behavior:
Clearing out lookup should cause parent record rollup to recalc and update to correct count.

**Comment by jamessimone** [comment]
@systemsfixer thanks for submitting this one! Should be an easy fix.

**Comment by jamessimone** [comment]
@systemsfixer I'm wondering if you can send me a log with `Is Rollup Logging Enabled` set to true on your Rollup Control for this situation? I have a test that should be reproducing this issue using the following rollup metadata:

```java
new Rollup__mdt(
      RollupFieldOnCalcItem__c = 'AnnualRevenue',
      LookupObject__c = 'Account',
      LookupFieldOnCalcItem__c = 'ParentId',
      LookupFieldOnLookupObject__c = 'Id',
      RollupFieldOnLookupObject__c = 'AnnualRevenue',
      RollupOperation__c = 'COUNT',
      CalcItem__c = 'Account'
)
```

But when I update the `Parent Account` field on an account, I am seeing the COUNT decrement accordingly on the old parent. A log will hopefully help to clear up the differences between the test I've written and the results you're seeing.

**Comment by jamessimone** [comment]
@systemsfixer I was able to identify and fix this issue - I will be looking to release the updated version in the next day or two
