### ISSUE TITLE
Ranking on "Rollup Order By" Cannot be marked Unique

### ISSUE THREAD

**Issue by melissajhansen** [jamessimone/apex-rollup#248]
Currently the Ranking__c on the new RollupOrderBy__mdt object is marked as Unique, but this enforces uniqueness across all records, not just the children of a particular rollup.

**Comment by jamessimone** [comment]
🤦‍♂️ I knew there was something I was forgetting with this one. Thanks for submitting this - I will probably be releasing the next version tomorrow with the fix.
