### ISSUE TITLE
Call CMDT rollups from flow

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#26]
It would be useful to be able to call CMDT rollups from flow. I would either want to pass in an id/name of a CMDT record (or maybe even a list), or supply the object/record and run all rollups configured for it (just like the apex trigger method works).

Thanks!

**Comment by jamessimone** [comment]
This is a great idea, though I want to talk it over with one of my other big Flow users prior to changing the existing invocable. It may be that I will simply add another apex action for this. I like the idea of supplying the object type and running all the rollups configured for it; unfortunately, as we discussed on SFXD, it will also be necessary in flow to supply the flow context variable (insert/update/delete) since (at present) Apex does not have the ability to divine that otherwise.

**Comment by solo-1234** [comment]
That sounds good! Passing in "insert" or "update" or "delete" is not a very big deal, and a lot less overhead than supplying all the fields which are stored in the CMDT

**Comment by jamessimone** [comment]
As part of this story, I'm going to switch over to using a CPE for Flow - my initial vision is using a toggle (off by default), which when clicked will eliminate many of the "required" fields in lieu of providing a CMDT DeveloperName / Id. Ideal state would be to also take advantage of a search feature to be able to select the `Rollup__mdt` row you are looking to use in the Flow on this part of the component.

The untoggled component will look largely as it does today, but using a CPE will allow for a richer user experience without sacrifices being made in terms of validation once the Invocable fields that are currently required are made optional by virtue of being able to choose between filling them out and simply supplying the CMDT Id/DeveloperName. This will also ensure backwards-compatibility with existing flows, which is great.

**Comment by jamessimone** [comment]
Keeping this up to date - @solo-1234 and I chatted on Discord today after receiving some key intel from @tsalb on the current state of CPE. In lieu of going down that route, I’ll expose another Invocable set of classes - both tightly integrated with Rollup - to allow for CMDT to be used within Flow as the rollup orchestrator, as well as allowing for all flow-based rollups to be loaded up prior to kicking off async work (#38)

**Comment by jamessimone** [comment]
@solo-1234 this is now possible in the latest version - thanks for your feedback and help with getting this released!

**Comment by solo-1234** [comment]
Awesome, looking forward to trying it out. Thanks!
