### ISSUE TITLE
Not checking between Batches

### ISSUE THREAD

**Issue by chrisBromma** [jamessimone/apex-rollup#318]
Hello James,

I had the problem, that I wanted to update all Records from one Object with a MIN Date from a second Object, that has a lookup on the first one.

I used the Full Recalc CMDT-driven Invocable" Apex action with a batch size of 350.
So I had 92 Batches.

The problem I got there is, that not all childs were in one Batch (my guess), so in the end not the smallest child was displayed on the parent. It was the second smallest.

Are the childs ordered. And can it be the case, that the childs are put in different Batches, without checking each other??

This is an issue, that is provending me from using the Rollup.

Do you have an idea and can check/ solve??

Thank you.
If you need some more info, just let me know.

**Comment by jamessimone** [comment]
Hi Chris, there is code in place that should be addressing the issue that you’re talking about. Out of curiosity, we’re you running the full recalc for multiple rollups at a time? If so, there’s the chance that there was a bug with the way that the calculation items (the children) were being retrieved which should be addressed in the release this morning. So, yes, some additional info would be helpful:

- what version were you using?
- Have you tried enabling the `Is Rollup Logging Enabled` field on the Org Default Rollup Control? If you have the Salesforce Dev console opened while the full recalc is running, the debug logs that get generated (filtering on “debug only”) will expose additional info that may be useful in diagnosing this issue
- If you were running multiple full recalcs with an older version - can you try running it with just the singular rollup you were having an issue with?

**Comment by jamessimone** [comment]
Not to worry, and welcome back! I hope you had a nice holiday. Glad to hear all is well - you know how to contact me if you run into any other issues!
