### ISSUE TITLE
Issue on Record Update with Upsert

### ISSUE THREAD

**Issue by jmusgrave33** [jamessimone/apex-rollup#326]
I have a record triggered flow that runs on event create or update and am using APEX Rollup to update three fields on the lead:  total number of events, first event date/time and last event date/time.  Everything works great on event create.  However, the field for total number of events does not get updated on event update unless I have the rollup operation is set to 'INSERT'.  The date/time fields update when the rollup operation is set to 'UPDATE.  I cannot figure out what I am doing wrong.

**Comment by jamessimone** [comment]
You’ll need to use `UPSERT` when your record triggered flow uses both contexts!

**Comment by jmusgrave33** [comment]
Thanks for the reply.  I had a typo above - it should been UPSERT, not UPDATE.  When I use UPSERT, the date/time fields update but the number field does not.  The number field only updates when I use INSERT.

**Comment by jamessimone** [comment]
@jmusgrave33 is the number field being changed during the update that you are performing? By default, that operation is diff-based, which means that you use the full recalc app to set the initial values, and then updates are only performed when the number field changes on an update. Does that make sense? Let me know!

**Comment by jamessimone** [comment]
@jmusgrave33 it's hard to say without looking at the output of the Apex debug logs - if you are using a Calc Item Where clause and an Event was updated to now match, then yes, the rollup count should increment. There are extremely detailed debug logs that get produced if you open up the Salesforce Developer Console and check off the `Is Rollup Logging Enabled` setting in the Org Default Rollup Control CMDT record.

If you are able to attach the logs produced by your Flow debugging, we should be able to see if there's an issue here.

**Comment by jmusgrave33** [comment]
Thanks, @jamessimone!  I really appreciate your help here.  I am away for the next few days.  I will get those logs to you next week.  Have a great weekend and Memorial Day!

**Comment by jamessimone** [comment]
No problem - thanks, and you too!

**Comment by jamessimone** [comment]
@jmusgrave33 fantastic - I'm going to close this one as resolved. I had a great weekend camping - hope you enjoyed yours, as well!
