### ISSUE TITLE
Attempt to de-reference a null object when rolling up from Recalculate Rollup tab

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#331]
I just upgraded to the newest version and am getting errors when trying to run multiple CMDT rollups from the app. It seems to work fine as long as the selected rollups all roll up to the same parent, but if they don't, I get an error.

Here's the stack trace:

```
Class.RollupParentResetProcessor.getRefinedQueryString: line 112, column 1
Class.RollupParentResetProcessor.<init>: line 33, column 1
Class.Rollup.buildFullRecalcRollup: line 2140, column 1
Class.Rollup.transformWrappedMetadataToFullRecalcRollups: line 2091, column 1
Class.Rollup.performSerializedBulkFullRecalc: line 488, column 1
18:58:16.232 (2702108996)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object
```

I've replicated this one two separate child objects (which both have rollups to multiple parent objects).

**Comment by jamessimone** [comment]
I found this while testing today, as well, and already have it fixed. It’ll be included in the next version!

**Comment by jamessimone** [comment]
@solo-1234 in the meantime, if you want to put the fix in place earlier, you can edit `RollupParentResetProcessor.getRefinedQueryString` and replace it with the following:

```java
  private static String getRefinedQueryString(String localQueryString, List<Rollup__mdt> matchingMeta) {
    isValidRun = false;
    String additionalFilters = '';
    if (matchingMeta.isEmpty() == false) {
      Map<String, SObjectField> fieldTokens = RollupFieldInitializer.Current.getSObjectFromName(matchingMeta[0].LookupObject__c)
        .getSObjectType()
        .getDescribe()
        .fields.getMap();
      for (Rollup__mdt meta : matchingMeta) {
        SObjectField token = RollupFieldInitializer.Current.getSObjectFieldByName(fieldTokens, meta.RollupFieldOnLookupObject__c);
        if (token.getDescribe().isFilterable()) {
          isValidRun = isValidRun || true;
          additionalFilters += meta.RollupFieldOnLookupObject__c + ' != null OR ';
        }
      }
    }

    return isValidRun ? '\nAND (' + localQueryString + additionalFilters.removeEnd(' OR ') + ')' : localQueryString;
  }
```

**Comment by solo-1234** [comment]
That was a quick fix - thanks!

**Comment by jamessimone** [comment]
@solo-1234 I edited the above with a slight tweak. I'll be looking to release this fix over the next few days.

**Comment by solo-1234** [comment]
Not sure if this is the same issue but I just got an error from a record triggered flow:

```
14:47:26.14 (1864180573)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.RollupParentResetProcessor.getRefinedQueryString: line 109, column 1
Class.RollupParentResetProcessor.<init>: line 33, column 1
Class.Rollup.buildFullRecalcRollup: line 2159, column 1
Class.Rollup.transformWrappedMetadataToFullRecalcRollups: line 2110, column 1
Class.Rollup.fillFullRecalcRollups: line 2077, column 1
Class.Rollup.processCustomMetadata: line 1940, column 1
Class.Rollup.performRollup: line 702, column 1
Class.RollupFlowBulkProcessor.addRollup: line 137, column 1
14:47:26.14 (1864206961)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object
```

**Comment by solo-1234** [comment]
@jamessimone what's wild is that since this error was triggered by an async path flow, it seems that SF keeps trying every so often!

**Comment by jamessimone** [comment]
Oh dear. I am just wrapping up the changes for the next version - it's been a bit slower going for a variety of reasons but I should have it released in the next few hours.

**Comment by solo-1234** [comment]
No worries - thanks for the quick service!

**Comment by jamessimone** [comment]
Of course!

**Comment by solo-1234** [comment]
No errors when running multiple rollups with different parents! Whew! Now let's see how the record triggered flows perform.

**Comment by solo-1234** [comment]
So far so good! I'll keep an eye on things and let you know if I run into any other issues.

Thanks for your help!
