### ISSUE TITLE
Minor annoyance with logging on first time use

### ISSUE THREAD

**Issue by KeithClarke** [jamessimone/apex-rollup#360]
I turned on logging when my first rollup was not working and got this message:

> 12:42:08.28 (789274685)|USER_DEBUG|[72]|FINE|Rollup v1.5.20: no-op, exiting early to avoid burning async job

and had to look at the source code to see that the cause was that I hadn't create this custom setting `RollupSettings__c.getInstance().IsEnabled__c == false`. A more explicit log message on that would have got me to the solution quicker. And its a pity that a first-time install isn't turned on by default.

(And yes I should have read the documentation more carefully.)

Another thought is for the CMDT to by default enable the feature via a checkbox, so that the setting is only needed when that checkbox is unchecked.

**Comment by jamessimone** [comment]
@KeithClarke the tiered approach to permissioning - user/profile/org with the custom setting as well as at the rollup level via the CMDT is preferred because it gives fine-grained control.

I will update the error message to be more explicit in the next version - thanks for submitting!

**Comment by jamessimone** [comment]
Ah, seeing your comment in the other thread and now have more context for the override you’re suggesting. I can add that as well.

**Comment by KeithClarke** [comment]
Thank-you @jamessimone.
