### ISSUE TITLE
Small bug on deploying this, when Task.Subject has a default value set

### ISSUE THREAD

**Issue by cybotjr** [jamessimone/apex-rollup#37]
Hello! 

First off, thank you so much for all your work in putting this together, and simplifying many dev lives!

It looks like RollupFieldInitializerTests on line 33:
   System.assertEquals('', initializer.getDefaultValue(Task.Subject), 'combobox');
Is expecting an empty string, but if there is a default set on the org, the assertion fails as the default is what is returned.
Removing a default value allowed deployment.

Unrelated Question: Last time i tried using CMDT, but the object list did not show Task nor Activities. Are those not supported with CMDT?

Thank you again!

**Comment by jamessimone** [comment]
@cybotjr I fixed the issue with the test for you just now - sorry about that!

Wow - about CMDT Entity Definitions, I actually did not know until this moment that they do not support lookups to Task and Event or User (and any other object in the mixed DML list). That's tragic to only be learning now of this downside to the CMDT approach, but for those objects I would recommend using `Rollup` by way of the static Apex methods exposed (or through Flow)!

Thanks for reporting, please let me know if you encounter any other issues!
