### ISSUE TITLE
Rollup calculation Issue when Is Full Record set

### ISSUE THREAD

**Issue by cbgrullon** [jamessimone/apex-rollup#370]
There is a problem when we have a Full Record Set rollup and we update a record that runs that Rollup, it is using the difference between the old and new value for the specific record that we've just updated.
Example:
Insert a record with 100 and the parent record will get 100: that's ok.
Update the record to 110 and the parent record will get 10: that's bad, should get 110.
I solved this in my work this could be a solution for you guys:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/31022904/194067220-edce8be8-c176-4a86-ae14-37ec6b6c7c51.png">
That is in RollupCalculator class, line 540.

**Comment by jamessimone** [comment]
@cbgrullon what kind of rollup operation is this? Also if you don’t have Is Full Record Set checked does this work as expected?

**Comment by jamessimone** [comment]
Ok, excellent. I will make the necessary fix for this next week; good to know you have options in the meantime. Thanks for reporting!

**Comment by cbgrullon** [comment]
Thank you
