### ISSUE TITLE
Error with RollupAsyncProcessor.lookupFieldOnCalcItem on execution from Flow

### ISSUE THREAD

**Issue by a-db** [jamessimone/apex-rollup#386]
Issue: Failure to find object field by using RollupAsyncProcessor.lookupFieldOnCalcItem
Error: APEX error for cannot find field for Object.Field__c
Location: New Partial sandbox
Execution: Triggered flow with a single non deferred Rollup Action

I was able to fix the error by doing a .getDescribe().getName() on this value prior to using it as the string in the object.get("field"). See code below. I haven't dug thoroughly through the code to determine if this should be changed in another location or if this error persists anywhere else. Curiously, this same Rollup Action configuration works without this modification if you use the manual recalculate rollup tab screen.

Code: RollupAyncProcess.getLookupRecordsCount() line 996
```
      Set<String> uniqueIds = new Set<String>();
      for (SObject calcItem : roll.calcItems) {
        if (calcItem.getSObjectType() == roll.calcItemType) {
          String fieldApiName = roll.lookupFieldOnCalcItem.getDescribe().getName();
          String lookupKey = (String) calcItem.get(fieldApiName);
          //String lookupKey = (String) calcItem.get(roll.lookupFieldOnCalcItem);
          if (String.isNotBlank(lookupKey)) {
            uniqueIds.add(lookupKey);
          }
        }
      }
```

**Comment by jamessimone** [comment]
@a-db thanks for submitting, I'll include the fix for this in the next version!

**Comment by jamessimone** [comment]
@a-db I've fixed this in the latest version - let me know if you encounter any other errors!
