### ISSUE TITLE
Add in Rollup Override metadata

### ISSUE THREAD

**Issue by jamessimone** [jamessimone/apex-rollup#393]
After talking with @attilah, add new CMDT type to shadow the base `Rollup__mdt` records which will allow for:

* CMDT-based configuration on objects where Entity and Field Definitions aren't available (Task, Event, User being the key ones)
* comma-separated field API names for the "lookup" fields on each object so that multiple fields can be used to form a "key"
* child relationship to `RollupOrderBy__mdt` to allow for tie-breaking on parent records if multiple match

**Comment by adepew** [comment]
Do you know if/when this might be available? I have some DLRS on Task I'd love to migrate to Apex Rollup.

**Comment by jamessimone** [comment]
Closing, given the existing workarounds for this
