### ISSUE TITLE
afterUndelete works but afterDelete does not

### ISSUE THREAD

**Issue by clint-rosetree** [jamessimone/apex-rollup#394]
Having some trouble understanding why I can't get the rollup to run the appropriate CMDT records using runFromTrigger() in the afterDelete or beforeDelete trigger operation types. I have no such problem with the afterUndelete trigger, but this compounds the problem by adding back a value that was never removed by the delete.

Am I missing something about how delete triggers work? I'm happy to provide additional information to help troubleshoot.

Thanks for making this framework available and the ongoing support and development!

**Comment by clint-rosetree** [comment]
I dropped a recalculate button on the parent object and the button works correctly.

**Comment by jamessimone** [comment]
@clint-rosetree are you sure your trigger has `before delete` listed as one of the defined trigger contexts? It sounds like you're using a trigger framework, but that would still require the object the trigger is defined on to have the proper contexts set up (otherwise it simply won't run for the defined context). After delete is only necessary if you're having Apex Rollup help out with standard object merges; I would double check the trigger in question to ensure `before delete` is defined. Let me know!

**Comment by clint-rosetree** [comment]
Thanks James, I'll switch back to the before delete context for the implementation and do some more testing. Definitely have the before delete context defined, but in my testing, I was running into the "System.FinalException: Record is read-only" error with the rollup there. This is a fairly old org, so there are plenty of places for failure, so I'll investigate where that error is really originating.

Will do some more debugging and report back what I find.

**Comment by jamessimone** [comment]
Hmm I replied via email but I guess it never sent ... let me know if you end up with a stacktrace for where you were seeing that `System.FinalException` - I'm assuming you are using a formula field somewhere in your rollup? There must be something on the delete code path that is trying to do the wrong there. We will get this fixed!

**Comment by clint-rosetree** [comment]
There are some formula fields involved with this one, so that may have been a source for the read-only error. I'm in the middle of testing some of the more complex scenarios, but so far, I've been able to get the delete rollup to fire correctly by moving the `Rollup.runFromTrigger()` call to the `before delete` trigger context in a few places.🤞

**Comment by clint-rosetree** [comment]
I'm no longer encountering this issue in my testing. The ultimate solution was to move everything into the `before delete` trigger context. I thought I had tried that already, but there may have been other issues I missed at that time.

Thanks for the support, @jamessimone

**Comment by jamessimone** [comment]
No problem - happy to help!
