### ISSUE TITLE
Batchable instance is too big: RollupAsyncProcessor.QueueableProcessor

### ISSUE THREAD

**Issue by david-bluefire** [jamessimone/apex-rollup#397]
We are getting the error "Batchable instance is too big", even though we are only updating a single record.

**Comment by jamessimone** [comment]
@david-bluefire what version are you using? Also, on your Org Default Rollup Control CMDT record, what is the Batch Chunk Size set to? What rollup action are you calling, as well - I've never heard of an update causing that kind of failure, and that includes for singular updates on a child associated with a parent with 80k+ records (this is currently an integration test I have set up).

In short - I'm surprised to hear that you're running into this issue, and I'm hopeful that it can be explained by something associated with your setup.

**Comment by david-bluefire** [comment]
We have a legacy trigger on the object in question that is doing some mysterious things. However, I reduced the Bach Chunk Size as well as the other fields in the Scalability section, and was able to mitigate the problem. Thank you for your suggestion!

**Comment by jamessimone** [comment]
No problem - happy to help!
