### ISSUE TITLE
Is there a limitation on number of child records in a rollup?

### ISSUE THREAD

**Issue by wwfch-cyrill** [jamessimone/apex-rollup#422]
I was just wondering if there is a limit, we'd need more than 100k records in a rollup. Other packages have issues with that as they run into a SOQL limit. 

Are the limits of this solution documented?

Thanks a lot.

**Comment by jamessimone** [comment]
Apex Rollup is not limited by things like the SOQL limits. 100k records is perfectly fine. One of the integration tests I use in the Apex Rollup pipeline features rolling up to a parent with 80k children.

**Comment by wwfch-cyrill** [comment]
Thanks a lot for clarifying.
