### ISSUE TITLE
CONCAT_DISTINCT is not working as expected when we make a delete

### ISSUE THREAD

**Issue by cbgrullon** [jamessimone/apex-rollup#424]
Take this rollup as an example:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/31022904/227324230-d50e280c-3b1f-4fdc-aa54-0c6791b7e324.png">

We have 3 values on the field Dummy Child Names
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/31022904/227323892-51a31957-81da-4701-902e-34b870724c4c.png">

But only two children
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/31022904/227324456-c3160682-6201-4859-b8f4-6ddd7b0ecf94.png">

The scenario is the following:

- We added 3 Child records to the parent with these names: 'Child 1', 'Child 2', and 'Child 3' > The parent record field gets the 3 values as expected.
- Then we delete the 'Child 3' and the parent record doesn't get updated with just the 'Child 1' and 'Child 2'

**Comment by jamessimone** [comment]
How are you calling Apex Rollup? From Flow or from Apex? Have you verified it is actually being called before delete?

**Comment by cbgrullon** [comment]
Yes, we are sure the call is being made from the trigger, we've tried using before/after(We read that we can also use the after context for delete) delete, and the same results for both of them.

**Comment by jamessimone** [comment]
@cbgrullon I will probably need to get some additional info from you - I haven't been able to reproduce the issue locally. Do you have any grandparent rollups running on the same child object? That would be an interesting piece of info where there might actually be a problem that I'm going to fix in the next version, but otherwise hearing a bit more about your setup and CMDT will help. Thanks!

**Comment by jamessimone** [comment]
Closing for now - I am absolutely happy to assist you at any time if this continues to be an issue, but I wasn't able to reproduce this problem locally across a variety of CONCAT_DISTINCT situations (insert/update/delete).
