### ISSUE TITLE
Bypass Validation Rules

### ISSUE THREAD

**Issue by jsteve06** [jamessimone/apex-rollup#440]
Is there a way to have the rollups bypass validation rules on the parent object? The product Rollup Helper has a custom setting that you can reference in the validation rule so that the rule is invalid when it updates the record. A lot of orgs that I work on have tons of validation rules so bypassing them to allow the rollups to work is crucial.

**Comment by jamessimone** [comment]
@jsteve06 you have a few options:

- provide a custom version of `RollupSObjectUpdater` (see the [example in the README](https://github.com/jamessimone/apex-rollup#other-rollup-plugins) for more info on that)
- reference the custom setting `RollupSettings__c` in your validation rules; you would need to update the `IsEnabled__c` flag as is appropriate in order for this to work as the VR bypass

Let me know if either of those approaches would work, or if you were thinking of something else. Thanks!

**Comment by jsteve06** [comment]
@jamessimone Well I am not a developer so option one is out :) 

Option 2 would work but I can't get it to work. If I reference it in the validation rule at either the org default or profile level, it is always on or off. So either I say ```
AND(ISPICKVAL(Active__c,''),
 $Setup.RollupSettings__c.IsEnabled__c = true )
```  and the validation rule still fires, or I set it to false and the validation rule works but is not bypassed when the rollup occurs. 

In my ideal world there would be another custom setting like "Bypass Validation Rule". That custom setting would be referenced in the validation rules. When the rollup updates the record  the setting would return 'true' otherwise it would return false. So then you'd just add $Setup.RollupSettings__c.Bypass_Validation_Rule = false to your validation rules. Hopefully that makes sense.

**Comment by jsteve06** [comment]
That would be great. Validation rules are the bane of my existence :)

**Comment by jamessimone** [comment]
@jsteve06 #441 added support for this - check the `Rollup Plugins` section of the README, or the release notes for more info!

**Comment by jsteve06** [comment]
This is awesome @jamessimone! I have it setup and working in my Dev org.  Took me a minute to figure out I needed to add a record to the Custom Meta Data rollup Plugin Parameter. Once I got that sorted out it worked like a charm. 

![image](https://github.com/jamessimone/apex-rollup/assets/75383279/b016d992-9ba3-4f14-991b-3334658c0a0f)

Thanks so much for adding this functionality.

**Comment by jamessimone** [comment]
No problem - couldn't have done it without you suggesting it! Thanks for making open source better by raising an issue and providing me with an excellent summary of what you were looking to do.
