### ISSUE TITLE
System.SObjectException: SObject row was retrieved via SOQL without querying the requested field

### ISSUE THREAD

**Issue by pyao-bwc** [jamessimone/apex-rollup#445]
I upgraded from 1.5.53 to 1.5.66 and one of our tests breaks with this exception:
05:52:24.438 (20410746673)|FATAL_ERROR|System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: Utility_Account_Subscription__c.Opportunity__r
Class.RollupRelationshipFieldFinder.areParentFieldsAlreadySet: line 752, column 1
Class.RollupRelationshipFieldFinder.getFullRecalcParents: line 729, column 1
Class.RollupRelationshipFieldFinder.getParents: line 189, column 1
Class.RollupAsyncProcessor.getCalcItemsByLookupField_rMap$$lString$$cRollup$$dCalcItemBag$$r_0RollupAsyncProcessor_1Set$$lString$$r: line 832, column 1
Class.RollupAsyncProcessor.process_rvoid_0List$$lRollupAsyncProcessor$$r: line 658, column 1
Class.RollupAsyncProcessor.performWork: line 345, column 1
Class.RollupAsyncProcessor.QueueableProcessor.execute: line 434, column 1

I downgraded to 1.5.63 and the test worked, so it looks like a more recent change caused this?

Here is the debug log at 1.5.66:
[debug log.txt](https://github.com/jamessimone/apex-rollup/files/11515838/debug.log.txt)

**Comment by pyao-bwc** [comment]
Thanks, that did it!

**Comment by jamessimone** [comment]
No problem, glad to hear it!
