### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by fefris** [jamessimone/apex-rollup#447]
Have 4.10 managed Nabula logger installed in instance, trying to install Plugin get the following error

1.  Invalid Upgrade.
The package you're installing depends on package 'Nebula Logger', version '4.8'. Install package 'Nebula Logger' in the target org before you install package 'Apex Rollup - Nebula Logger'.

**Comment by jamessimone** [comment]
@fefris unfortunately, the plugins aren't cross-compatible with namespaced versions of packages. Have you looked at the [source code](../tree/main/plugins/NebulaLogger) for the plugin at all, though? It's a single class that could easily be created in your org (and registered with the corresponding Rollup Plugin CMDT record) with the updates referring to `Logger` with the Nebula namespace. Let me know if that will work for you!

**Comment by jamessimone** [comment]
@fefris wanted to follow up with you about this one, to see if you had any thoughts on my original response above?

**Comment by jamessimone** [comment]
Closing for now - feel free to get back to me if the proposed workaround isn't feasible for your org!
