### ISSUE TITLE
Both unmanaged and managed package installation failed in sandbox

### ISSUE THREAD

**Issue by Jung-BEP** [jamessimone/apex-rollup#453]
Apex Rollup summer 23 Updates Release

Problem:

1.  Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
Rollup: Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

2.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupAsyncProcessor: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

3.  Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupCalcItemReplacer: Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

4.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupCalcItemSorter: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

5.  Dependent class is invalid and needs recompilation:
 Class RollupCalcItemSorter : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupCalculator: Dependent class is invalid and needs recompilation:
 Class RollupCalcItemSorter : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

6.  Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupCurrencyInfo: Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

7.  Invalid date
RollupDateLiteral: Invalid date

8.  Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupDeferredFullRecalcProcessor: Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

9.  Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupEvaluator: Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

10.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFieldInitializer: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

11.  Dependent class is invalid and needs recompilation:
 Class RollupLogger : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFinalizer: Dependent class is invalid and needs recompilation:
 Class RollupLogger : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

12.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFlowBulkProcessor: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

13.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFlowBulkSaver: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

14.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFlowFullRecalcDispatcher: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

15.  Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFullBatchRecalculator: Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

16.  Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupFullRecalcProcessor: Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

17.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupLogger: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

18.  Dependent class is invalid and needs recompilation:
 Class RollupRepository : Dependent class is invalid and needs recompilation:
 Class RollupQueryBuilder : Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupMetaPicklists: Dependent class is invalid and needs recompilation:
 Class RollupRepository : Dependent class is invalid and needs recompilation:
 Class RollupQueryBuilder : Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

19.  Dependent class is invalid and needs recompilation:
 Class RollupFullBatchRecalculator : Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupParentResetProcessor: Dependent class is invalid and needs recompilation:
 Class RollupFullBatchRecalculator : Dependent class is invalid and needs recompilation:
 Class RollupAsyncProcessor : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

20.  Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupQueryBuilder: Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

21.  Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupRecursionItem: Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

22.  Dependent class is invalid and needs recompilation:
 Class RollupQueryBuilder : Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupRelationshipFieldFinder: Dependent class is invalid and needs recompilation:
 Class RollupQueryBuilder : Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

23.  Dependent class is invalid and needs recompilation:
 Class RollupQueryBuilder : Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupRepository: Dependent class is invalid and needs recompilation:
 Class RollupQueryBuilder : Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

24.  Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupSObjectUpdater: Dependent class is invalid and needs recompilation:
 Class RollupCurrencyInfo : Dependent class is invalid and needs recompilation:
 Class RollupCalcItemReplacer : Dependent class is invalid and needs recompilation:
 Class RollupFieldInitializer : Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

25.  Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date
RollupSchedulable: Dependent class is invalid and needs recompilation:
 Class Rollup : Dependent class is invalid and needs recompilation:
 Class RollupEvaluator : Dependent class is invalid and needs recompilation:
 Class RollupDateLiteral : Invalid date

26. (rollupUtils) Unable to find Apex action class referenced as 'Rollup'.
rollupUtils: Unable to find Apex action class referenced as 'Rollup'.

**Comment by jamessimone** [comment]
@Jung-BEP I'm unable to reproduce this issue. If you are installing via the package installation screen, I would advise using the advanced options and specifying only compiling apex classes in the package. If you are doing a package upgrade from a version prior to 1.5, you may need to uninstall the existing package and reinstall because each minor version from (from 1.4 -> 1.5, for example) comes with breaking changes that necessitate further upgrade work.

**Comment by Jung-BEP** [comment]
Thank you @jamessimone  It is a logical suggestion. Didn't try that option. If the installation goes well, i will close out the issue.

**Comment by Jung-BEP** [comment]
hi @jamessimone 
I think I found the cause. Our org is enabled with Custom Fiscal Year. So "SELECT Id FROM Opportunity WHERE CloseDate = THIS_FISCAL_YEAR" will flag as invalid.

When this following snippet was executed in Anonymous window, Invalid Date error displayed.
List<Opportunity> oppList = [SELECT Id FROM Opportunity WHERE CloseDate = THIS_FISCAL_YEAR LIMIT 10];
system.debug(oppList);

I will close the issue as it is specific to an org with Custom Fiscal Year enabled.
Thank you!
