### ISSUE TITLE
Add support for grandchild to grandparent rollups (and potentially more)

### ISSUE THREAD

**Issue by jamessimone** [jamessimone/apex-rollup#46]
This feature request from @elements:

Currently, rollup assumes that the only `1 : many` relationship is from the parent to each "child" object in the hierarchy - but it would be great to allow something like rolling up fields from Opp Line Items straight to Account, for example; cutting out the Opportunity middleman. 

For multiple "jumps" between objects, the relationship between the "lookup field" (since it can be a string or Id) to the parent object would have to be established (possibly using "Apex map" syntax a la @tsalb's [Custom Column Labels in lwc-utils](https://github.com/tsalb/lwc-utils/wiki/soqlDatatable:-Custom-Column-Labels), or with another CMDT that's related to `Rollup__mdt`). Being able to use filtering criteria on the in-between objects should also be supported.

**Comment by jongpie** [comment]
One additional thought on this - since rollup now supports initiating rollups from parent records (PR #43), it probably makes sense to do the same for grandparent records, i.e., allow rollups on a grandparent record to trigger recalculating rollups that are driven by grandchild records.
