### ISSUE TITLE
Record Trigger Flow not executing rollup

### ISSUE THREAD

**Issue by bchovan73** [jamessimone/apex-rollup#468]
Hi James,
We have a custom object that has a Master/Detail relationship to ServiceAppointment with has a Lookup to Work Order. The flow is executing the rollups as expected. Basically we have fields on the custom object(JHA Onsite Person) that we want SUM'd up on the WorkOrder which is a grandparent object. To the best of my knowledge we have everything set up properly. The record triggered flow runs on Update and has an apex action for performing the CMDT driven rollups and an action for processing the deferred rollups. Attaching some screenshots and a sample apex log.EDIT TO ADD: The rollup works when I use the Rollup Button on the rollup App.
![flow4](https://github.com/jamessimone/apex-rollup/assets/63372405/a40e400c-98d7-4552-a3f7-7979088c6dc8)
![flow3](https://github.com/jamessimone/apex-rollup/assets/63372405/9f344bc7-636c-40c2-a7bd-0aba210eb8e6)
![flow2](https://github.com/jamessimone/apex-rollup/assets/63372405/840daaee-d145-421b-be81-8c7b33300f41)
![flow1](https://github.com/jamessimone/apex-rollup/assets/63372405/4d91f22e-5554-4e00-a9f7-5de85fdade2e)
![orgdefaultsscreenshot](https://github.com/jamessimone/apex-rollup/assets/63372405/c8eb8418-286e-4d0a-bbf1-f8c495b0e035)
![rollupcmdtscreenshot](https://github.com/jamessimone/apex-rollup/assets/63372405/113c8de6-aed7-4744-b8c4-f5629be72980)

[apex-07L7b00000PhXPVEA3.log](https://github.com/jamessimone/apex-rollup/files/12195857/apex-07L7b00000PhXPVEA3.log)

**Comment by jamessimone** [comment]
@bchovan73 any chance you haven't enabled the Rollup Setting custom setting org default? It's reporting a "no op" no operation, which is typically from the custom setting not having been enabled.

**Comment by bchovan73** [comment]
I am pretty sure I did but I will double check when I get back in front of my screen. Thank you.

Sent from my iPhone

On Jul 28, 2023, at 1:52 PM, James Simone ***@***.***> wrote:

﻿

@bchovan73<https://github.com/bchovan73> any chance you haven't enabled the Rollup Setting custom setting org default? It's reporting a "no op" no operation, which is typically from the custom setting not having been enabled.

**Comment by bchovan73** [comment]
@jamessimone I have double checked and the custom setting was indeed enabled.
![customsetting1](https://github.com/jamessimone/apex-rollup/assets/63372405/b9ab9af4-4baa-43cb-ba95-dc6f90b6c1ed)

**Comment by jamessimone** [comment]
Oh! @bchovan73 are you using the right Rollup action? You want the CMDT action? I want to make sure you're not using the base action (where you have to supply ALL the data). If you are using the base action, that might explain the "no-op!" message in the logs.

**Comment by bchovan73** [comment]
Yes I am using the CMDT action.

**Comment by jamessimone** [comment]
You are using the CMDT action, apologies for asking that as I can see you're using the right action in the log - is `Work_Order__c` a custom field on your Service Appointment object to get around limitations with `ParentId` ? There's nothing obviously wrong with your setup, but something about it is causing the rollup(s) in question to be removed prior to actually being stored for processing. 

I've never seen something like this - ideally, I'd love to know what's going on in the `Rollup.processCustomMetadata` method, as that's the most likely place where wires could be getting crossed. I guess, as well, that a good place to start would be validating that the code gets into that method. I don't know how comfortable you are with Apex debugging, but I'm happy to assist in any which way. One _other_ thing to check is the message returned with Flow - right _after_ the log message that shows up in what you attached, it's also possible for the output for the Flow to have `No records to rollup, returning early` show up. I'm confident that we can figure out what's happening here and get this working for you.

**Comment by bchovan73** [comment]
That field was definitely created to get around the polymorphic lookup limitations.

**Comment by jamessimone** [comment]
No problem, happy to assist!
