### ISSUE TITLE
convert-dlrs-rules.apex fails when run with the namespaced version install

### ISSUE THREAD

**Issue by MarcDBehr** [jamessimone/apex-rollup#474]
I installed the namespaced version of apex-rollup (04t6g000008So66AAC) and then tried to run the convert-dlrs-rules.apex script via anonymous apex and got an error:

```
Starting Execute Anonymous Apex

Error: Line: 4, Column: 14
Error: Invalid type: RollupControl__mdt
```

I assume that the script (and probably deactivate-converted-dlrs-rules.apex)  needs to be modified to call the namespaced references. It would be helpful if a namespaced version of the scripts be provided for users that are not familiar with how to do so.

**Comment by jamessimone** [comment]
@MarcDBehr that's a great call, I can add a namespace-compatible script in the next release

**Comment by jamessimone** [comment]
@MarcDBehr [there's a link now](https://github.com/jamessimone/apex-rollup/commit/a3a6e2354a909f52da0c20ea8400fd6f2cc81a34) to a working version of those files. Including that as a resource for you in the event that the next release is held up.
