### ISSUE TITLE
rollup from apex without a trigger

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#48]
It would be neat if we could call rollups from anywhere in apex - even without a trigger, pass in a record collection and trigger context, and let it run all the CMDT rollups for that record collection. That would make this much more flexible in terms of where it's running and on which records.

It's possible to use the flow invocable action from apex, but it involves quite a bit of code:
```        RollupFlowBulkProcessor.FlowInput rollupInput = new RollupFlowBulkProcessor.FlowInput();
        rollupInput.recordsToRollup = myRecordCollection;
        rollupInput.rollupContext = 'INSERT';
        rollupInput.deferProcessing = false;
        List <RollupFlowBulkProcessor.FlowInput> rollupInputs = new List <RollupFlowBulkProcessor.FlowInput> {rollupInput};
        List <Rollup.FlowOutput> rollupOutputs = RollupFlowBulkProcessor.addRollup(rollupInputs);
        System.debug('rollupOutputs: ' + rollupOutputs);
```

It would be awesome if we could get a more concise way, something to the tune of this:
```Rollup.runFromApex(List <sObject> records, String rollupContext, Boolean deferProcessing)```

Thanks!

**Comment by jamessimone** [comment]
@solo-1234 slight deviation from the API you proposed, but you should be all set:

- I decided against passing a boolean in for deferral. Until I hear that this is necessary in this context, using CMDT in combination with Apex should be the preferring mechanism for "batching" rollup operations via these methods; there are other imperative Apex methods if batching is needed for other scenarios
- I don't like strings, and Apex offers us the type-safety of the `TriggerOperation` enum - for your use-case, I believe you're looking for `TriggerOperation.AFTER_INSERT` - more info can be found in the [release notes](/releases/tag/v1.1.7)!

**Comment by solo-1234** [comment]
Thanks! I wasn't planning on using deferral, I just included it because it was included in the invocable. 

Those enums sound exactly right!

**Comment by jamessimone** [comment]
No problem - enjoy!
