### ISSUE TITLE
Getting apex error: 'RollupFullBatchRecalculator' for job id '7073C000034XqRD' : expecting a right parentheses, found 'AND'

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#492]
I have been receiving these error messages fairly consistently and not sure what is the cause.  None of my rollups have an "AND" in the WHERE clause statement.

![image](https://github.com/jamessimone/apex-rollup/assets/104730171/87f9c73f-105f-42ff-ad0c-aee6ac6fe7a6)

**Comment by jamessimone** [comment]
This should be cleared by following the advice in #491

**Comment by baobao917** [comment]
Thanks!  No longer receiving the error message.  I wasn't aware that it made a difference that I structure my WHERE clause as:

AcctSeed__Age__c IN ('0-Current', '1-30 Days', '31-60 Days')

vs

AcctSeed__Age__c='0-Current' OR AcctSeed__Age__c='1-30 Days' OR AcctSeed__Age__c='31-60 Days'
(This is how it was written in DLRS so that's what I used)
