### ISSUE TITLE
Incorrect rollup calculation

### ISSUE THREAD

**Issue by Phanishankarp** [jamessimone/apex-rollup#496]
[apex-07L8N000004SZ3wUAG.log](https://github.com/jamessimone/apex-rollup/files/12619882/apex-07L8N000004SZ3wUAG.log)
[apex-07L8N000004SZ3rUAG.log](https://github.com/jamessimone/apex-rollup/files/12619883/apex-07L8N000004SZ3rUAG.log)
[apex-07L8N000004SZ3iUAG.log](https://github.com/jamessimone/apex-rollup/files/12619886/apex-07L8N000004SZ3iUAG.log)
[apex-07L8N000004SZ3hUAG.log](https://github.com/jamessimone/apex-rollup/files/12619889/apex-07L8N000004SZ3hUAG.log)
I have built custom metadata based flow implentation like below to rollup(Count) the child records whose Terminated Date field value is less than TODAY
<img width="784" alt="image" src="https://github.com/jamessimone/apex-rollup/assets/26519788/a45008d4-e177-4860-8c61-a4c8d3a5474c">

Success Scenario:

1. At present there 'Count of Terminated Records': 2 out of 6 Total records
2. Update Terminated Date to '16-Aug-2023'(<TODAY) 
3. Calculation happened correctly and now 'Count of Terminated Records': 3 out of 6 Total records

Failure Scenario:

1. Currently Count of Terminated Records': 3 out of 6 Total records
2. I have modified above mentioned record's terminated date to '16-Sep-2023'(>TODAY)
3. **Calculation is incorrect** and now 'Count of Terminated Records': **1** but it should be **2**

I am unable to proceed further because of this issue. Can anyone assist?

**Comment by Phanishankarp** [comment]
Attached are logs generated:
[apex-07L8N000004SZ3wUAG.log](https://github.com/jamessimone/apex-rollup/files/12619796/apex-07L8N000004SZ3wUAG.log)
[apex-07L8N000004SZ3rUAG.log](https://github.com/jamessimone/apex-rollup/files/12619797/apex-07L8N000004SZ3rUAG.log)
[apex-07L8N000004SZ3iUAG.log](https://github.com/jamessimone/apex-rollup/files/12619799/apex-07L8N000004SZ3iUAG.log)
[apex-07L8N000004SZ3hUAG.log](https://github.com/jamessimone/apex-rollup/files/12619801/apex-07L8N000004SZ3hUAG.log)

**Comment by jamessimone** [comment]
I will have a look on Monday, should be an easy fix if there's an issue here

**Comment by jamessimone** [comment]
@Phanishankarp this is fixed with the latest update
