### ISSUE TITLE
Questions: Missing Object in Custom Metadata Types

### ISSUE THREAD

**Issue by sylg** [jamessimone/apex-rollup#499]
Hi James, first of all, fantastic job on this package. 

However, I'm setting things up and I'm trying to do a roll-up based on Tasks, but Task (or Activity) is missing in the Child Object or Parent Object dropdown when I create a rollup via the Custom Metadata Types way.

Rollup backfill works fine and can see the task. This is running in a sandbox will full permission on the account. 

Any ideas with Task is missing from the dropdown?

**Comment by jamessimone** [comment]
@sylg thanks so much! That means a lot. Unfortunately, Task, Event and User aren't supported through the Custom Metadata records for Apex Rollup - but you can still create rollups for them using either records in memory within Apex, or by using the base flow action. I'd read through the README and the Wiki looking at where Task is called out.

I believe I also cover this a bit in the YouTube videos about setting up Apex Rollup. Hope that helps!

**Comment by sylg** [comment]
James, thank you for the reply in 8 minutes. I skimmed the readme but now I see the relevant sections. Thanks for this and for pointing me toward the solution

**Comment by jamessimone** [comment]
Happy to help!
