### ISSUE TITLE
Unable to install Apex Rollup: Apex compile failure

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#507]
I'm attempting to install Apex Rollup into a sandbox and am getting the following install failures:

Your request to install package "Apex Rollup Fixes where clause parsing for nested OR statements" was unsuccessful. None of the data or setup information in your [salesforce.com](http://salesforce.com/) organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: ServiceOne, Inc (00D7e00000JhepI)
User: Cloud Coastal (0054w00000AL5nm)
Package: Apex Rollup (04t6g000008C71X)

Problem:

1.  Apex compile failure
Apex class S1ProductConsumedControllerTest: line 14, column 58: Method does not exist or incorrect signature: void getLocations(Id) from the type S1ProductConsumedController

2.  Apex compile failure
Apex class S1ProductConsumedControllerTest: line 15, column 60: Method does not exist or incorrect signature: void getWorkOrder(Id) from the type S1ProductConsumedController

3.  Apex compile failure
Apex class S1ProductConsumedControllerTest: line 19, column 37: Method does not exist or incorrect signature: void saveProductsConsumed(String) from the type S1ProductConsumedController

![image](https://github.com/jamessimone/apex-rollup/assets/104730171/e1838969-1a7a-446f-9b2d-824d937ffb00)

**Comment by jamessimone** [comment]
If you go into the advanced options when installing the package, you can choose to only compile the Apex in the package. Those classes are not in the package!
