### ISSUE TITLE
When reparenting child records, rollup not calculating correctly on old parent record

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#514]
When changing the parent (Parent 1) on a child record(s) to a new parent (Parent 2), the rollup calculation on the old parent (Parent 1) is not calculating correctly.

Please see video.

https://www.loom.com/share/8636d7cf96164f05a14e4cf761010ec2?sid=cc8b9063-5a81-4144-8e30-2b520fb654b8

Parent 1 (before reparenting)
![image](https://github.com/jamessimone/apex-rollup/assets/104730171/ebd7bd0c-d3d4-40cb-a84c-9b1c4effd278)

Parent 2 (after reparenting)
![image](https://github.com/jamessimone/apex-rollup/assets/104730171/213a0090-3927-4624-bab0-8c7a2b4cfd0a)

**Comment by jamessimone** [comment]
I had a preliminary fix for this lined up for v1.6.1 but ended up backing it out for that release because it would only have worked for the case @baobao917 had brought up, and not _all_ cases generally. I plan to complete this work in the next version.

**Comment by baobao917** [comment]
Thanks @jamessimone ! Tested it and this is now fixed as of v1.6.2

**Comment by baobao917** [comment]
Hi @jamessimone I tested this issue and there still is a calculation error on the old parent.  Pls see video below.

https://www.loom.com/share/1268bd6b971b4600be5eb7b96892d423?sid=ac3b3389-1b85-45c7-9d7f-4859a6ae6417

I don't seem to be able to reopen this issue.  What do you want me to do?

P.S. I left a comment on here earlier (which I've deleted) stating I tested this and it was fixed but that comment was meant for another issue.  Hopefully that didn't confuse you.

**Comment by baobao917** [comment]
@jamessimone Excellent! Tested this against v1.6.3 and the old parent calculated correctly!  Thanks!

**Comment by jamessimone** [comment]
@baobao917 great! I had tested this in your UAT environment prior to closing, glad we got this one sorted out.
