### ISSUE TITLE
Allow us to sort columns in the Recalculate Rollup tab table of rollups

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#521]
The tab with the list of rollups is really useful. If we could sort columns (specifically the Parent Object column) it would make it easier to see what's what, especially when one child object rolls up to multiple parent objects.

**Comment by jamessimone** [comment]
That's a great idea. I'll be making that change as part of #520

**Comment by solo-1234** [comment]
Thank you!
