### ISSUE TITLE
Flow trigger error - Apex error occurred: System.NullPointerException: Attempt to de-reference a null object

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#529]
Hi @jamessimone - I am starting to get an error in the sandbox (which you have access to).   It just started occurring and don't know why.  I don't see any null values and the flow trigger had been working just fine recently.  I'm wondering if perhaps it is related to any changes you made?  

![image](https://github.com/jamessimone/apex-rollup/assets/104730171/1ae064ca-86a6-494b-bf6a-5954e983ef1b)

COPIED AND PASTED INFO FROM EMAIL

Flow Error Details

Flow Details

Flow API Name: Billing_AS_CU_Trigger_Apex_Rollup
Type: Autolaunched Flow
Version: 2
Status: Active
Org: ServiceOne, Inc (00D7e00000JhepI)

Flow Interview Details

Interview Label: Billing - AS - CU - Trigger Apex Rollup 10/27/2023, 3:00 PM
Interview GUID: 9274a5791ffc5d87f44f364e965f18b72b2ae32-4cfc
Current User: Cloud Coastal (0054w00000AL5nm)
Start time: 10/27/2023, 3:00 PM
Duration: 1 seconds

How the Interview Started
Cloud Coastal (0054w00000AL5nm) started the flow interview.
API Version for Running the Flow: 58
Some of this flow's variables were set when the interview started.
$Record = AcctSeed__Billing__c (a0h7e000005EtwAAAS)
ASSIGNMENT: Add record to record collection variables
{!varR_ColRecords} Add {!$Record}
{!varR_ColOldRecords} Add {!$Record__Prior}
Result
{!varR_ColOldRecords} = "[AcctSeed__Billing__c (a0h7e000005EtwAAAS)]"
{!varR_ColRecords} = "[AcctSeed__Billing__c (a0h7e000005EtwAAAS)]"

**Comment by jamessimone** [comment]
To be safe, I would upgrade to the official version of 1.6.1 to be sure everything is up to date. I switched over to a scratch org while working on a few of the other issues you'd reported but it's possible that things in your sandbox were left in an incomplete state.

**Comment by jamessimone** [comment]
@baobao917 is this still an issue? I wasn't able to reproduce

**Comment by baobao917** [comment]
@jamessimone No it was resolved when I upgraded to v1.6.1.  Thanks!  I'll close the issue.
