### ISSUE TITLE
Error upgrading from 1.5.64 to 1.6.6

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#548]
Hi! I'm trying to upgrade the unmanaged package and I got this error:

```
Your request to install package "Apex Rollup Flow optimizations continued" was unsuccessful. None of the data or setup information in your [salesforce.com](http://salesforce.com/) organization was affected.

Problem:

1.  Apex compile failure
Apex class RollupSObjectUpdaterTests: line 9, column 5: Constructor not defined: [RollupSObjectUpdater].<Constructor>(Schema.SObjectField)

2.  Apex compile failure
Apex class RollupSObjectUpdaterTests: line 19, column 7: Constructor not defined: [RollupSObjectUpdater].<Constructor>(Schema.SObjectField)
```

Any ideas how to fix this? TIA

**Comment by jamessimone** [comment]
I would uninstall the extra test plugin package and do the base package upgrade before reinstalling the updated extra test plugin package

**Comment by solo-1234** [comment]
Thanks for responding! That sounds like a good idea, except that I don't have any test packages installed... I just have Apex Rollup and Apex Rollup - Nebula Logger.

**Comment by solo-1234** [comment]
In the list of apex classses in setup, `RollupSObjectUpdaterTests` was installed in 2021 and isn't part of any package (no little icon to the left of the class name). Should I delete it?

**Comment by jamessimone** [comment]
Ah yes - I don't package _all_ of the test classes so the ones that aren't listed as part of a package are safe to delete

**Comment by solo-1234** [comment]
That worked - thank you!
