### ISSUE TITLE
RollupAsyncProcessor is creating a second queueable job per apex invocation

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#551]
Hi @jamessimone ,

We are experiencing an issue where two different apex classes are trying to create queueable jobs.
- RollupAsyncProcessor (ApexRollup apex class)
- BT_TransactionService.createJournalEntry (custom apex class)

Our understanding is that during any individual apex invocation, Salesforce will only allow one queueable job to be added per apex invocation.  Therefore we're getting thie error "Too many queuable jobs added to the queue: 2"
![image](https://github.com/jamessimone/apex-rollup/assets/104730171/d4ea377a-fdc1-4e5c-8bc8-cebd41be4201)

We're not sure how to handle this b/c we don't understand what the RollupAsyncProcessor class is doing.  I'm not sure why it's firing at all b/c the objects being affected aren't any which we currently have rollups configured for.  Any suggestions/insight you have would be appreciated.

I have added the debug logs which show the two classes being called. To make it a bit clearer, I have also added a second attachment which shows the two portions where those classes are called. 
- [S1 debug log.txt](https://github.com/jamessimone/apex-rollup/files/13813928/S1.debug.log.txt)

- [S1 Queuable calls.txt](https://github.com/jamessimone/apex-rollup/files/13813929/S1.Queuable.calls.txt)

**Comment by jamessimone** [comment]
@baobao917 Based off of the `S1 debug log.txt` file, I can see lines like this: `FLOW_START_INTERVIEW_BEGIN|65532f2f0cf49dcbc13b5adf61d718cac549c47-4e1c|Work Order - AS - CU - Trigger Apex Rollup` which would seem to indicate that records associated with rollups are in fact being updated. By default, Apex Rollup uses Queueables - however, you can also have it use Batch classes or even synchronous executions by modifying the Rollup Control record (either the Org Default, or a control record specifically for these rollups) by changing the `Should Run As` picklist value.

**Comment by baobao917** [comment]
Thanks @jamessimone .  I temporarily deactivated the rollup which impacted the work order object and that temporarily solved our issue.  It's curious b/c the process that we kicked off shouldn't have touched the work order object so I'm going to have to dig into our other custom class and see why it seems to be firing your RollupAsyncProcessor class.

Quick question on the rollup control should run as "batchable".  How does this work exactly? I'm familiar with running it synchronously and as queueable but not as batchable.  I know for sure that running it synchronously will not work for us for this particular rollup since we have so many automations on the work order object which is one reason why ApexRollups option to use queueable was a great fit

There isn't a lot of information in the rollup control section on batchable.
![image](https://github.com/jamessimone/apex-rollup/assets/104730171/810722df-f6ba-483e-8b78-37827dc09dcc)

Thanks!

**Comment by jamessimone** [comment]
In this case, Batchable should do the same thing as starting up a Queueable - it's a bit slower to perform the entire operation, but that shouldn't really matter here.

**Comment by baobao917** [comment]
Thanks @jamessimone.  I tested and ran the rollup using a Rollup Control where Should Run As = Batchable.  The grandparent rollup and the reparenting all seemed to function correctly.  
![image](https://github.com/jamessimone/apex-rollup/assets/104730171/a391deb3-b4a5-4f7f-8a44-e8b0451ec357)

![image](https://github.com/jamessimone/apex-rollup/assets/104730171/680fd880-b40c-42cb-96e4-fa2636a7f351)


One quick question....I observed that in the Apex Jobs, it still appeared to run as 'Queueable'.  Is that correct?
![image](https://github.com/jamessimone/apex-rollup/assets/104730171/8aca3dc9-3b8d-4d3f-b9b3-29fa0572bc15)

**Comment by jamessimone** [comment]
Yes, that's correct. It's a bit of a hack, but it only starts as a batch in order to get going properly.

I will revamp the documentation about this - you've hit upon a weakness in the framework, and with Queueables in general; namely, that it can detect when it will be a problem to start up as a Queueable when all of your code has finished running, but if _other_ code _after_ Apex Rollup blindly fires off a Queueable, that can be an issue.

**Comment by jamessimone** [comment]
You can leave it open - I'll close this after updating the README. Thanks!
