### ISSUE TITLE
Scheduled Job exception Missing dependent object: Class: RollupEvaluator.AndConditionalGrouping

### ISSUE THREAD

**Issue by nsinghCloudera** [jamessimone/apex-rollup#572]
Hi @jamessimone,

Recently we have updated rollup package in our salesforce instance and after that we are getting below exception for scheduled job.

Scheduled job 'Escalation Rollups (Hourly)' threw unhandled exception.

caused by: line -1, column -1: The configuration of your org has changed, please reload the page.  Missing dependent object: Class: RollupEvaluator.AndConditionalGrouping

**Comment by jamessimone** [comment]
@nsinghCloudera I would re-schedule the job. It sounds like it's using an older version of Apex Rollup that isn't compatible with the current version!

**Comment by jamessimone** [comment]
@nsinghCloudera let me know if you need more help with this - re-scheduling the job should fix this issue

**Comment by nsinghCloudera** [comment]
@jamessimone This is fiexed. 
Thank you @jamessimone for your help.
