### ISSUE TITLE
Error upgrading from 1.6.2 to 1.6.18

### ISSUE THREAD

**Issue by ChrisBegleyYale** [jamessimone/apex-rollup#573]
Hi! I'm trying to upgrade the unmanaged package and I got this error:

```
Problem:

1.  Apex compile failure
Apex class RollupRepositoryTests: line 7, column 49: Variable does not exist: RollupRepository.PermissionLevel

2.  Apex compile failure
Apex class RollupTests: line 2447, column 26: Variable does not exist: shouldRunAsBatch

3.  Apex compile failure
Apex class RollupTests: line 2900, column 26: Variable does not exist: shouldRunAsBatch
```

Any ideas how to fix this? Thanks!

**Comment by jamessimone** [comment]
@ChrisBegleyYale I think I need to create a new version of the Extra Code Coverage plugin for you. Apologies - let me get that taken care of and I'll release an updated version

**Comment by ChrisBegleyYale** [comment]
@jamessimone thank you, I appreciate it!

**Comment by jamessimone** [comment]
@ChrisBegleyYale new version is shipping out at the moment - you'll probably need to uninstall the old version of the Extra Code Coverage plugin, update Apex Rollup to v1.6.19, and then re-install the latest version. Apologies for the multi-step process, but that will resolve this issue for you.

**Comment by ChrisBegleyYale** [comment]
@jamessimone thank you, unfortunately the upgrade from 1.6.2 to 1.6.19 failed as well:

```
1.  Apex compile failure
Apex class RollupRepositoryTests: line 7, column 49: Variable does not exist: RollupRepository.PermissionLevel

2.  Apex compile failure
Apex class RollupTests: line 2447, column 26: Variable does not exist: shouldRunAsBatch

3.  Apex compile failure
Apex class RollupTests: line 2900, column 26: Variable does not exist: shouldRunAsBatch

4.  Apex compile failure
Apex class RollupTests: line 3004, column 18: Variable does not exist: orgAsyncJobsUsed
```

We don't have the Extra Code Cover plugin installed

**Comment by jamessimone** [comment]
@ChrisBegleyYale I see - did you ever deploy the `extra-tests` folder yourself to your org? It's odd that you would have those tests included in the package, as they are not included by default. You may need to delete those test classes prior to proceeding

**Comment by ChrisBegleyYale** [comment]
@jamessimone I'm not sure where they came from, but deleting the classes worked. Thanks for your help!

**Comment by jamessimone** [comment]
no worries, happy to be able to help!
