### ISSUE TITLE
Custom Object Rollup Logger Plugin missing "Is Rollup Logging Enabled?"

### ISSUE THREAD

**Issue by adepew** [jamessimone/apex-rollup#578]
I've installed the rollup logger plugin and was following the instructions, however I am not seeing the "Is Rollup Logging Enabled?" option.

![image](https://github.com/jamessimone/apex-rollup/assets/30325923/c259dfa8-ab75-4569-b97b-0b1c63f50b34)

**Comment by jamessimone** [comment]
This is toggled on the Rollup Control record!

**Comment by adepew** [comment]
> This is toggled on the Rollup Control record!

D'oh, thanks! 🤦
