### ISSUE TITLE
COUNT_DISTINCT Falls Back to Default Value on Deletion

### ISSUE THREAD

**Issue by PhilTerz** [jamessimone/apex-rollup#581]
I've set up a great-grandchild COUNT_DISTINCT rollup to count the Member__c (Contact lookup) field on an object Chapter Member underneath a State. It is working great for inserting those Chapter Member junctions, but on deleting one, the rollup field goes to blank (or zero if I enter the Full Recalculation Default Number Value). 

My triggers for the objects Chapter Member, Chapter, and State program should all have the required trigger contexts. 
`trigger ChapterMemberTrigger on Chapter_Member_JB__c(after insert, after update, before delete, after undelete)`

![Screenshot 2024-04-12 at 9 20 56 AM](https://github.com/jamessimone/apex-rollup/assets/8586058/871bcea4-da43-449e-8bdd-dfd8d1dede6a)

When I change the Rollup Operation to just COUNT, keeping the triggers the same, both insert and delete is working fine.

**Comment by jamessimone** [comment]
I will take a look, I should be able to get to this by early next week. Thank you for reporting!

**Comment by jamessimone** [comment]
@PhilTerz this should be fixed as of #582 !

**Comment by PhilTerz** [comment]
@jamessimone Working as expected on my end. Thanks for such a fast turnaround!

**Comment by jamessimone** [comment]
Great news, thanks for letting me know
