### ISSUE TITLE
Add the ability to select an existing CMDT record when recalculating

### ISSUE THREAD

**Issue by jongpie** [jamessimone/apex-rollup#59]
The "Recalculate Rollup" component currently requires you to enter all of the rollup details. This works great with having full control - but if you've already defined a `Rollup__mdt` record with all of the details, it's a little repetitive to have to re-enter it. Ideally, this component should have 2 options to select from

1. **Manual Entry** - the existing functionality. This is definitely nice to have, and it's required in order to do rollups for objects like task, event & user since they're not currently supported in CMDT `EntityDefinition` fields
2. **Select Existing Rollup** - new functionality. When this option is used, the component should show a list of `Rollup__mdt` records (maybe displayed in a dropdown?) for the admin/user to select

In either scenario, I think you'd still want to be able to specify a `WHERE` clause, so the existing input "Where Clause SOQL Filters (Optional)" should be displayed for both options.

**Comment by jongpie** [comment]
Follow-up thought on this - I initially wrote that the list of `Rollup__mdt` records could maybe displayed in a dropdown, but what do you think about instead designing it so you can select & run multiple `Rollup__mdt` records at the same time? I think it would have to be limited to `Rollup__mdt` records with the same `CalcItem__c`, but it'd be handy to be able to select & recalculate several rollups all at once.

**Comment by jamessimone** [comment]
Yeah, I think that's a great idea. We can just group the `Rollup__mdt` records by `CalcItem__c` and return the list of those names - then it's as simple as selecting the option you want from a `lightning-combobox` element. I love it! Should be a fun one to work on.

**Comment by dhoechst** [comment]
Was just coming over to log this specific issue. I built 4 rollups from the same `CalcItem__c` and doing the initial rollup was kind of a pain to reenter them. In my case, I wanted the where clause to be the one specified in the `Rollup__mdt` records which was slightly different for each one.

**Comment by jamessimone** [comment]
@dhoechst excellent feedback to add into the mix. I’m planning to knock this one out this weekend!

**Comment by jamessimone** [comment]
@dhoechst in the event that you need to use the full recalculation again, this is now released with #61 ! Thanks again for stopping by.
