### ISSUE TITLE
Switching rolled up parents resulting in duplicates on prior parent

### ISSUE THREAD

**Issue by thomasadchapman** [jamessimone/apex-rollup#599]
I've successfully duplicated this issue with a couple of different object scenarios, but not completely thoroughly. 

I have a rollup from child to parent, all managed via flows calling CMDT, when a child is reparented, the correct value for the prior-parent is doubled - which points to regression, but I cannot see the triggering flow firing twice in debug. Flow setup: 

![image](https://github.com/jamessimone/apex-rollup/assets/38044091/d5b08d6e-03c1-43e1-b4e9-b254d8c79edb)
![image](https://github.com/jamessimone/apex-rollup/assets/38044091/3c2adc34-b59b-4196-93c0-a8cd535ec767)
![image](https://github.com/jamessimone/apex-rollup/assets/38044091/fff5fff6-8e38-4630-b095-3d500ea148de)

with a simple CMDT record: 

![image](https://github.com/jamessimone/apex-rollup/assets/38044091/79e12cc2-8979-43d9-8db8-4cdf46ddd0be)

Manually recalculating the prior parent resolve the miscalculation

[apex-07LTu000002YI3pMAG.log](https://github.com/user-attachments/files/15839412/apex-07LTu000002YI3pMAG.log)
[apex-07LTu000002YJK3MAO.log](https://github.com/user-attachments/files/15839413/apex-07LTu000002YJK3MAO.log)
[apex-07LTu000002YLNUMA4.log](https://github.com/user-attachments/files/15839416/apex-07LTu000002YLNUMA4.log)
[apex-07LTu000002YLNVMA4.log](https://github.com/user-attachments/files/15839417/apex-07LTu000002YLNVMA4.log)
[apex-07LTu000002YNNdMAO.log](https://github.com/user-attachments/files/15839419/apex-07LTu000002YNNdMAO.log)
[apex-07LTu000002YNNeMAO.log](https://github.com/user-attachments/files/15839420/apex-07LTu000002YNNeMAO.log)
[apex-07LTu000002YNPFMA4.log](https://github.com/user-attachments/files/15839423/apex-07LTu000002YNPFMA4.log)
[apex-07LTu000002YNQrMAO.log](https://github.com/user-attachments/files/15839424/apex-07LTu000002YNQrMAO.log)
[apex-07LTu000002YNSTMA4.log](https://github.com/user-attachments/files/15839425/apex-07LTu000002YNSTMA4.log)

**Comment by jamessimone** [comment]
@thomasadchapman I will take a look - thanks for submitting! I'll let you know if I have any questions

**Comment by jamessimone** [comment]
@thomasadchapman I'm noticing that your rollup version is several dozen behind the latest: you're running #460, and (notably), I can tell you that I added a test for this specific issue in #493 (ten versions past where you're at, but still far behind the present version). I'd recommend upgrading - it should fix your issue!

**Comment by thomasadchapman** [comment]
@jamessimone Well that's embarrassing! Problem resolved... Will endeavour to not be quite such an idiot in future.

**Comment by jamessimone** [comment]
Hey now, no worries! Glad to hear we're good - thanks again for submitting!
