### ISSUE TITLE
Async jobs triggered when the Rollup Control Setting is set to run Synchronously 

### ISSUE THREAD

**Issue by kechetino** [jamessimone/apex-rollup#618]
Hi,

I set my Org Default Rollup Control (Which I am using for all my rollups) to run synchronously but whenever the child records are updated/inserted, it seems the RollupAsyncProcessor or the RollupFullBatchRecalculator is always triggered. Is this the expected behaviour or these jobs should not be running if the Control Setting is set to synchronous?

![image](https://github.com/user-attachments/assets/5fba83b2-400f-40d1-a194-15c320cd3f39)
![image](https://github.com/user-attachments/assets/9234c6c0-285f-4139-a927-c110ad10abe6)

**Comment by jamessimone** [comment]
@kechetino do you have any more info? The only thing I can think of, off-hand, is that there are some checks done prior to running a rollup synchronously which may be preventing a sync rollup from occurring. This can occur when your sync insert _also_ triggers an update or delete on that same object. This forces the second rollup (the update/delete) to be run asynchronously to ensure that the parent-level information in the database is shown correctly for field-level history purposes.

**Comment by jamessimone** [comment]
It's certainly possible. Migrating users have reported strange behavior previously when Apex Rollup _and_ DLRS are both triggered from the same child object, but I don't think there would be issues if it were just the same _parents_ being updated from different children objects

**Comment by kechetino** [comment]
Thanks @jamessimone - Will give it a proper test when fully migrated and see if the issue persists.
