### ISSUE TITLE
Child Object Where Clause not working with a flow

### ISSUE THREAD

**Issue by techps** [jamessimone/apex-rollup#621]
I created the Custom Metadata Type for rolling up the number of payments (custom object) to Contact records (direct parent). For the "Child Object Where Clause" I set to **Status__c NOT IN ('Cancelled' , 'Deferred', 'Opted Out')**. When I run the recalculation everything works as expected, however, when I create a payment and a flow triggers, it omits the filter and counts all payments despite of the status. Here is the flow (when Payment is created or updated)
![image](https://github.com/user-attachments/assets/cc423670-1717-488a-8337-5e5366eab627)
![image](https://github.com/user-attachments/assets/533143a9-ce38-43a4-b7d3-9f1feb1aab36)

**Comment by jamessimone** [comment]
@techps your screenshot isn't showing the actual where clause, but try using the following:

```
Status__c NOT IN ('Cancelled','Deferred','Opted Out')
```

**Comment by techps** [comment]
@jamessimone Thank you, do you suggest to add the where clause on the flow? I have it on the custom metadata
![image](https://github.com/user-attachments/assets/63aae70b-644e-4d44-b157-98f6772cff5d)

**Comment by jamessimone** [comment]
On the where clause is fine, I just think there's an issue with the trailing space and comma in it at present

**Comment by techps** [comment]
My bad, it appears there is a second trigger that does the calculation as well. Everything works as expected. Thank you!
