### ISSUE TITLE
Error when merging Accounts

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#623]
Getting the following error when attempting to merge two Accounts:
![image](https://github.com/user-attachments/assets/85c21147-78bb-487a-b1d1-af4aefb11092)

We couldn't merge these accounts.
ApexRollupAccountTrigger: execution of AfterDelete caused by: System.IllegalArgumentException: Where clause entered incorrectly: (Age2__c IN ('0-Current', '1-30 Days', '31-60 Days')) AND AcctSeed__Customer__c = :recordIds AND Age2__c IN ('0-Current', '1-30 Days', '31-60 Days') Exception: List index out of bounds: 19 Class.RollupEvaluator.WhereFieldEvaluator.recursivelyCreateConditions: line 396, column 1 Class.RollupEvaluator.WhereFieldEvaluator.createConditions: line 294, column 1 Class.RollupEvaluator.WhereFieldEvaluator.<init>: line 239, column 1 Class.RollupEvaluator.getWhereEval: line 30, column 1 Class.Rollup.getWrappedMeta: line 2169, column 1 Class.Rollup.processCustomMetadata: line 2065, column 1 Class.Rollup.runFromApex: line 1762, column 1 Class.Rollup.runFromTrigger: line 1690, column 1 Trigger.ApexRollupAccountTrigger: line 3, column 1 Class.RollupEvaluator.WhereFieldEvaluator.createConditions: line 298, column 1 Class.RollupEvaluator.WhereFieldEvaluator.<init>: line 239, column 1 Class.RollupEvaluator.getWhereEval: line 30, column 1 Class.Rollup.getWrappedMeta: line 2169, column 1 Class.Rollup.processCustomMetadata: line 2065, column 1 Class.Rollup.runFromApex: line 1762, column 1 Class.Rollup.runFromTrigger: line 1690, column 1 Trigger.ApexRollupAccountTrigger: line 3, column 1

What's also odd is that on both Accounts, there are no child billing records (which is what this rollup is referencing). We have v1.6.33 installed of ApexRollup.

**Comment by baobao917** [comment]
Also confirmed it is not limited to these specific Accounts.  Any Accounts I attempt to merge get this error.

**Comment by jamessimone** [comment]
@baobao917 good to hear from you, though I'm sorry it's under these circumstances. at the moment you can disable by setting `Is Merge Reparenting Disabled` to true on the org default rollup control record. I am trying to wrap up work on a few other reported issues at the moment so I won't get the chance to look at this issue this week. If it's alright with you, hopefully we can coordinate a time that I can take a look once I've finalized v1.6.34!

**Comment by baobao917** [comment]
@jamessimone No worries.  When you get a chance to look at it.  I think you mean 'Is Merge Reparenting Enabled' = TRUE.  It is already set to that.
![image](https://github.com/user-attachments/assets/389171c7-a219-47d6-8e23-957ff4032efd)

**Comment by jamessimone** [comment]
@baobao917 my mistake - you can uncheck that to unblock yourself in the meantime
