### ISSUE TITLE
RollupAsyncProcessor for job ID 707VI00000pPWLK. : Too many query rows: 50001

### ISSUE THREAD

**Issue by baobao917** [jamessimone/apex-rollup#625]
I've gotten these errors from time to time and do not know what it pertains to or how to resolve.

![image](https://github.com/user-attachments/assets/db98ebf0-d882-42a1-8ae5-5534c44ed259)

**Comment by jamessimone** [comment]
@baobao917 I've put in a potential fix for this in the latest version. I'll hold off on closing this until you're sure this is working, though.

**Comment by baobao917** [comment]
Hi @jamessimone - Thanks for the update.  I'm not really sure how to reproduce the error as it just sort of happens from time to time.  You can close this issue and if it pops up again, I can just open a new issue.
