### ISSUE TITLE
First/Last Rollup Operation Issues

### ISSUE THREAD

**Issue by pjfront** [jamessimone/apex-rollup#63]
I set up a CMDT Rollup where the `Order By (First/Last)` field name was different from the `Rollup Field On Calc Item`. When I treid to trigger the rollup by creating a new record of the relevant calc object, I receive an AfterInsert/AfterUpdate error `System.SObjectException: SObject row was retrieved via SOQL without querying the requested field`.

I was able to reproduce this error with different objects. Every time `OrderByFirstLast__c` on the CMDT Rollup record was not the same as `RollupFieldOnCalcItem__c`, I could not save new records of the object specified as the calc item.

(apologies if this is not the correct format for logging issues like this, it's my first time opening an issue on a project!)

**Comment by jamessimone** [comment]
@pjfront this is the perfect way to report this ! I will have this fixed shortly

**Comment by jamessimone** [comment]
@pjfront you should be all set - sorry about that!

**Comment by pjfront** [comment]
Amazing, thank you so much for the quick response!

**Comment by jamessimone** [comment]
No problem - enjoy using rollup!
