### ISSUE TITLE
RollupDateLiteralTests is failing with DevOps deployments

### ISSUE THREAD

**Issue by ChrisBegleyYale** [jamessimone/apex-rollup#638]
Hello,
Some of our Apex Class deployments are failing on the following DevOps Center test:

`RollupDateLiteralTests.shouldWorkForYesterday(): System.AssertException: Assertion Failed: Literal defined as ref: 2024-11-03 05:00:00 | bound: 2024-11-04 04:59:59 should have matched 2024-11-03 04:59:59 for = for timezone America/New_York : Expected: true, Actual: false`

I updated to the latest version of the plugin but that didn't seem to help. Is this a known issue? Thanks.

**Comment by jamessimone** [comment]
@ChrisBegleyYale this test just started failing for me, today, as well. It's a classic Daylight Savings issue. I have the fix for this prepared for #636 - that being said, it will "fix itself" tomorrow. I apologize that this was an issue for today though

**Comment by ChrisBegleyYale** [comment]
@jamessimone no problem and thanks for the quick reply! It did fix itself as you said.
