### ISSUE TITLE
Miscalculation of date boundary due to time zone differences

### ISSUE THREAD

**Issue by KomalJha01** [jamessimone/apex-rollup#640]
I've attached a PDF that explains that boundary cases of date are not handled correctly.
In my case, I want to calculate the Amount (Ask_Amount__c is the lookup on contact) on the contact which is N_YEARS_AGO so when I'm taking the boundary values of dates then It does not give the correct amount.

Further details are explained in the pdf.

[_Miscalculation of Date Boundary due to Time Zone Differences (1).pdf](https://github.com/user-attachments/files/17827157/_Miscalculation.of.Date.Boundary.due.to.Time.Zone.Differences.1.pdf)

**Comment by jamessimone** [comment]
Thanks for the PDF. I will take a look!

**Comment by KomalJha01** [comment]
This is my own code.
Yes but when are calculating the range of date value within the boundaries then
`dateVal > this.bound.dateGmt() && dateVal > this.ref.dateGmt();`
And then .dateGMT() gives the time shift issue results in the wrong calculation.
![image](https://github.com/user-attachments/assets/e49f548b-42a5-44f0-8423-95bd69b3dcd5)

**Comment by jamessimone** [comment]
Got it! I will get this fixed - I've had limited time this week but hoping to be able to dedicate a few hours tomorrow

**Comment by KomalJha01** [comment]
Thanks!! @jamessimone
