### ISSUE TITLE
Error Logging and Reporting

### ISSUE THREAD

**Issue by dhoechst** [jamessimone/apex-rollup#68]
When a rollup fails, it would be nice to log this error and the parent record that wasn't successfully updated. This could let an admin review the errors and try to fix whatever might be the problem. When things are running asynchronously, these errors just kind of disappear. For example, I see some errors in my Apex Jobs view, but I don't know which record failed or even what caused the problem. I just see `Attempt to de-reference a null object`.

**Comment by jamessimone** [comment]
Also great feedback, I agree. While there are multiple places where it's possible for a rollup to fail, if you're experiencing issues specifically related to individual records being rolled up, that sounds like a good place to start.  If you _do_ have a stacktrace, that would also be handy as far as diagnosing any potential issues!

**Comment by dhoechst** [comment]
I think the problem is I'm not aware when something fails. It would take a lot of work to find records that don't have the right values. Rollup Helper has this error handling and reporting feature and is what made me think it would be good here. 

Here's a screen shot:
![image](https://user-images.githubusercontent.com/1051263/114121266-4a669b00-98ab-11eb-8983-3a2f6440f575.png)

**Comment by jamessimone** [comment]
Ah, interesting. I’ll have to create a lightweight logger and error custom object to support this

**Comment by jamessimone** [comment]
@dhoechst - broke ground on this story this morning after much ado in the way of delay. @jongpie and I had talked about this feature last week and we came to a few conclusions:

- all logging options involving custom objects will come as "plugins," or additional unmanaged packages
- the default logging option will continue to only use the Apex debug logs
- it will be possible for users to come up with their own logging integrations; to that point, I'll also provide an additional unmanaged package hooking `Rollup` up to a logging solution like [Nebula Logger](https://github.com/jongpie/NebulaLogger)
