### ISSUE TITLE
Detect Context and Override Rollup Control Accordingly

### ISSUE THREAD

**Issue by dhoechst** [jamessimone/apex-rollup#69]
If you are in a batch Apex job that causes a rollup to fire, you might get an error `First error: Too many queueable jobs added to the queue: 2`. When determining whether or not to enqueue the job, check to see if you have room to enqueue another job. Check [Limits.getQueueableJobs](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_limits.htm#apex_System_Limits_apex_System_Limits_getQueueableJobs) and Limits.getLimitQueueableJobs(). If there are no more queueable jobs, then either run the rollup in batch (but maybe check limits there too) or synchronously.

**Comment by jamessimone** [comment]
@dhoechst yes I agree - I have been thinking about this particular edge case quite a bit and was leaning toward the either/or with going into whichever async version we weren’t in if it was safe to do so, or trying to proceed sync. Thanks for reporting! I’ll get to this shortly.
