### ISSUE TITLE
Problem deploying v1.2.4 

### ISSUE THREAD

**Issue by dhoechst** [jamessimone/apex-rollup#70]
It looks like the grandparent rollup test is failing due to ordering of the values that are getting concatenated. I took a quick glance at the code and didn't see a quick way to fix it. I'm wondering if you should use lists and sets for the concatenate operation. That seems to be a bigger rework, though.

System.AssertException: Assertion Failed: Grandparent rollup should have worked!: Expected: One, Two, Actual: Two, One
Stack Trace: Class.RollupTests.shouldAllowGrandparentRollupsFromParent: line 3039, column 1

**Comment by dhoechst** [comment]
Also, ordering the values might be nice in general.

**Comment by jamessimone** [comment]
@dhoechst I will have this fixed in a few minutes - thanks for reporting

**Comment by jamessimone** [comment]
@dhoechst you should be all set on this one - apologies for the delay, also started investigating #69 to see if I could squeeze it into v1.2.5 but ended up deciding to take more time on it. Thanks again for reporting these issues, we will work together to get everything resolved for you!
