### ISSUE TITLE
Full Rollup using CMDT results in "SObject row was retrieved via SOQL without querying the requested field"

### ISSUE THREAD

**Issue by dhoechst** [jamessimone/apex-rollup#71]
I'm trying out the full rollup using CMDT with different where clauses. The batch is failing because of the dreaded error `SObject row was retrieved via SOQL without querying the requested field`. I'm not sure if it matters, but the field I'm filtering on is a formula field. 

I have 4 CMDT records for one calc item. Each one has a different where clause.

Here's my stack trace:

FATAL_ERROR System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: [fieldname]
FATAL_ERROR Class.RollupEvaluator.WhereFieldCondition.getFieldValue: line 481, column 1
FATAL_ERROR Class.RollupEvaluator.WhereFieldCondition.equals: line 415, column 1
FATAL_ERROR Class.RollupEvaluator.AndConditionalGrouping.conditionallyEquals: line 374, column 1
FATAL_ERROR Class.RollupEvaluator.ConditionalGrouping.equals: line 336, column 1
FATAL_ERROR Class.RollupEvaluator.WhereFieldEvaluator.matches: line 134, column 1
FATAL_ERROR Class.Rollup.filter: line 2140, column 1
FATAL_ERROR Class.Rollup.<init>: line 221, column 1
FATAL_ERROR Class.Rollup.RollupAsyncProcessor.<init>: line 318, column 1
FATAL_ERROR Class.Rollup.loadRollups: line 1962, column 1
FATAL_ERROR Class.Rollup.getRollup: line 1844, column 1
FATAL_ERROR Class.Rollup.getDelegatedRollup: line 2037, column 1
FATAL_ERROR Class.RollupFullBatchRecalculator.execute: line 35, column 1

**Comment by dhoechst** [comment]
Also, I wish I could spend more time and actually provide a pull request for some of these issues. Sorry!

**Comment by jamessimone** [comment]
@dhoechst not to worry, you’ve been super helpful. There will always be a time for contributions! This error you’re reporting is present on v1.2.5, yes? I have some tests that are specific to formula fields working but the “where clauses” are something of a special beast. Are each of your calc item where clauses simply filtering on that one field, or are they more complex? Also - do you have any way to tell (this may be impossible so apologies in advance) if the error is occurring on the SECOND `Rollup__mdt`?

One potential way to validate this would be to try with only a single CMDT record but if that’s a pain to go and delete what you already have, no worries.

Also of note is the starting place for the error — the full batch recalculator. Were you trying to calculate the initial values for the parent records via the Rollup app when you got this error, or was it from a record being inserted/updated etc?

Thank you!

**Comment by dhoechst** [comment]
Well, I had managed to get v1.2.4 installed before you made the fix, so the line numbers in the stack trace correspond to that release. I'm still having the error in v1.2.5. 

Here's a screen shot of the error with the new line numbers:
![image](https://user-images.githubusercontent.com/1051263/114122142-e644d680-98ac-11eb-8d62-9dd9987998fd.png)

The where clause is simple: `Has_SOX_Impact__c = TRUE`. Just for grins, I was able to replicate the logic of the formula field in the where clause instead and now it is telling me a different field wasn't selected. As for which CMDT record it is failing, I'm not sure.

**Comment by dhoechst** [comment]
Oh, and to answer a question I missed. I'm trying to do a full rollup via the Rollup app.

**Comment by jamessimone** [comment]
Ok got it - that makes more sense. Should be able to patch this one up tomorrow, hopefully

**Comment by jamessimone** [comment]
@dhoechst you should be all set on this one!
