### ISSUE TITLE
Unlocked Package

### ISSUE THREAD

**Issue by dhoechst** [jamessimone/apex-rollup#72]
It would be awesome to provide an unlocked package for installing into orgs rather than relying on Andy's GitHub deploy tool. This would make it easier to uninstall and upgrade.

**Comment by jamessimone** [comment]
@dhoechst that’s the plan 😅. This is also on the near-term roadmap. I’ll try to get the 2GP setup within the next week!

**Comment by jamessimone** [comment]
@dhoechst wish granted! Too bad Github strips the default styles for HTML buttons, I'll have to spruce up the "click to install package" options in the Readme ...
