### ISSUE TITLE
Add a way to convert DLRS CMDT rules to Rollup CMDT rules

### ISSUE THREAD

**Issue by jongpie** [jamessimone/apex-rollup#84]
Since several people/orgs are switching from DLRS to Rollup, it'd be great to have a way to automatically convert existing DLRS rules to Rollup rules. Not all orgs will need this extra code, so this should probably be kept outside of the main [`rollup`](https://github.com/jamessimone/apex-rollup/tree/main/rollup) directory.

As far as implementation goes, it will probably be a new batch job that re-uses some logic in my [CustomMetadataSaver](https://github.com/jongpie/CustomMetadataSaver) repo to deploy the CMDT records. This will allow admins to convert DLRS rules directly within an org (instead of having to use SFDX or other external tools)

**Comment by jamessimone** [comment]
Awesome, love this
