### ISSUE TITLE
Ability to specify Concatenate/Concatenate Distinct Delimiter

### ISSUE THREAD

**Issue by daveerickson** [jamessimone/apex-rollup#90]
I am intrigued by this project, and am currently using the DLRS tool. I currently use a semicolon to concatenate values in fields that are ingested by other methods. I'm wondering if this feature is on the roadmap. Thanks.

**Comment by jamessimone** [comment]
@daveerickson this feature is already supported! There is a field on the `Rollup__mdt` Custom Metadata where you can add in a custom concat delimiter - `Concat Delimiter`. Please let me know if you have any questions, there should be good support for using custom delimiters across the entirety of this project.

**Comment by jamessimone** [comment]
@daveerickson in looking through the Readme just now, I am realizing how this issue probably came to be filed - if you install Rollup, you’ll see the Concat Delimiter field on the custom metadata - but I somehow forgot to include it in the Readme information! I will update the Readme with the latest release, v1.2.14, which should go out this weekend

**Comment by daveerickson** [comment]
Thank you for the response. You are completely correct, my review of the Readme had me thinking this was not configurable. I appreciate you quick reply.

**Comment by jamessimone** [comment]
@daveerickson no problem
