### ISSUE TITLE
System.SObjectException: Field xxx is not editable

### ISSUE THREAD

**Issue by mickster04** [jamessimone/apex-rollup#97]
System.SObjectException: Field Score__c is not editable
Class.RollupEvaluator.RecursiveUpdateEvaluator.matches: line 637, column 1
Class.RollupEvaluator.CombinedEvaluator.matches: line 90, column 1

when running a MDT rollup against a lead from custom child object I am presented the above exception. the field in question is of type Formula (Number)

the code 
        clonedItem.put(this.metadata.RollupFieldOnCalcItem__c, calcItem.get(this.metadata.RollupFieldOnCalcItem__c));
seems to be setting the field to manage recursion tracking?

I don't quite follow but obviously what I would like to know is how do I get this roll up to work? Do i need to replicate the field somehow, or is this not even possible with rollup? or is there some further config I can do 

Please ask questions as I don't know what information you might need here. I also had a read through the doco and couldn't see anything that mentioned my situation?

**Comment by jamessimone** [comment]
Hey @mickster04, thanks for reporting this. I will fix this tomorrow morning, also as part of the v1.2.17 release. Apologies that you’re running into this issue; for now you can get this working by commenting out line 49 in RollupEvaluator.cls - thanks for reporting, and apologies for the problem!

**Comment by mickster04** [comment]
Awesome! thanks! I did wonder if it was possible to manage recursion with just the ID? anyway, I look forward to your update!
